xml/src1/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Annual_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Annual Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Annual Conference</relationshipLabel>
        <relationshipName>Annual_Conference</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>District</description>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District</relationshipLabel>
        <relationshipName>District</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Jurisdiction</description>
        <label>Jurisdiction</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jurisdiction</relationshipLabel>
        <relationshipName>Jurisdiction</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>District</fullName>
        <active>true</active>
        <description>A grouping of local churches led by a District Superintendent</description>
        <label>District</label>
    </recordTypes>
    <recordTypes>
        <fullName>Jurisdiction</fullName>
        <active>true</active>
        <description>The regional body made up of Annual Conferences</description>
        <label>Jurisdiction</label>
    </recordTypes>
</CustomObject>

xml/src1/objects/Annual_Conference__c.object
<CustomObject>
    <description>Getting Annual Conferences depending on Episcopal Area</description>
    <fields>
        <fullName>Annual_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organization Annual Conference</description>
        <label>Annual Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Annual Conferences (Annual Conference)</relationshipLabel>
        <relationshipName>Annual</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Conference</label>
    <nameField>
        <displayFormat>AC-{00000000}</displayFormat>
        <label>AC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Conferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Annual_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A geographical area and organization. Defines a region that includes all UM churches and ministries in that area.</description>
        <inlineHelpText>Enter contact&apos;s home annual conference (where membership held)</inlineHelpText>
        <label>Annual Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Appointment_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Most clergy will serve in the annual conference where their membership is held.  However, those in Extension Ministry/ABLC could serve in a different annual conference than where their membership is.Only clergy members should have an assigned Appointment Conference.  The Annual Conference where Contact is appointed to serve.</description>
        <inlineHelpText>If different from Annual Conference, enter annual conference where contact is appointed (working conference)</inlineHelpText>
        <label>Appointment Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Working Conference)</relationshipLabel>
        <relationshipName>Working_Conference</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When a District is selected,Annual Conference and Jurisdiction should select automatically.
The UMC District that the Contact belongs to or where they are serving. The districts in an annual conference varies depends on the size of the Annual conference.Typically 60–80 churches are in a district. Each district is supervised by a district superintendent and Each church or other ministry setting in an annual conference is part of a district.</description>
        <inlineHelpText>Select district where appointed</inlineHelpText>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (District (Organization))</relationshipLabel>
        <relationshipName>District_Members_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Number__c</fullName>
        <description>Emergency Contact Number for Contacts</description>
        <label>Emergency Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Jurisdictions in U.S. (North Central, Northeast, South Central, Southeast, and Western).A group of annual conferences within a geographical region in the United States.</description>
        <inlineHelpText>Auto-populated from annual conference</inlineHelpText>
        <label>Jurisdiction</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jurisdiction</relationshipLabel>
        <relationshipName>Jurisdiction_People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>Middle Name of the Contact</description>
        <label>Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>Social Security Number</description>
        <inlineHelpText>Enter Contact&apos;s Social Security Number.  May be entered with or without dashes.</inlineHelpText>
        <label>SSN</label>
        <length>11</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Salutation_Other__c</fullName>
        <description>Other Salutation for the contact</description>
        <inlineHelpText>Enter salutation if not found in Picklist</inlineHelpText>
        <label>Salutation Other</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

xml/src1/objects/Position__c.object
<CustomObject>
    <description>Positions in Organization Types</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Position the contact is holding</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position_Title__c</fullName>
        <description>Position in the organizations</description>
        <inlineHelpText>Select title that best describes contact&apos;s position</inlineHelpText>
        <label>Position Title</label>
        <picklist>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant to the President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator/Business Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Discipleship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy/Social Justice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa University Senate Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Conference Treasurer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant District Superintendent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate District Superintendent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Pastor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHECM Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bishop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bishops Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board DHE Vice Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board DOM Vice Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board of Trustees Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Recording Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Co-Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Registrar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Staff Network Position</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Manager of General Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camp Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping &amp; Retreat Ministries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campus Minister</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Superintendent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{00000000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <recordTypes>
        <fullName>District</fullName>
        <active>true</active>
        <description>Positions of the district office</description>
        <label>District</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src1/classes/Handler_Contact.cls
// test
public with sharing class Handler_Contact
{
    /* Rocky Assad : TA616
    public static void UpdateAppointmentConferences(List<Contact> newContacts)
    {
        // iterate through contacts
        for(Contact contact : newContacts)
        {
            // if appointment is null but not annual conference
            if(contact.Appointment_Conference__c == null && contact.Annual_Conference__c != null)
            {
                contact.Appointment_Conference__c = contact.Annual_Conference__c; 
            }
        }
    }
    */
    
    public static void UpdateContact_AC_JD_District_APC(List<Contact> newContacts)
    {
        // all parents and annual conferences
        Set<Id> districtIds = new Set<Id>();
        for(Contact newContact : newContacts)
        {
            if(newContact.District__c != null)
            {
                districtIds.add(newContact.District__c);
            }
        }
        // get all available districts
        Map<Id, Account> districts = new Map<Id, Account>([select Id, ParentId, Parent.ParentId from Account where id in :districtIds]);
        
        Set<Id> annualConferenceIds = new Set<Id>();
        for(Contact newContact : newContacts)
        {
            if(newContact.Annual_Conference__c != null)
            {
                annualConferenceIds.add(newContact.Annual_Conference__c);
            }
        }
        // get all available annual conferences 
        Map<Id, Account> annualConferences = new Map<Id, Account>([select Id, ParentId from Account where id in :annualConferenceIds]);
        
        // iteratate through contacts updating annual conferences and jurisdictions
        for(Contact contact : newContacts)
        {
            // check if district is null
            if(contact.District__c != null)
            {
                // check if parent (annual conference) is null
                if(districts.get(contact.District__c).ParentId != null)
                {
                    // set the annual conference to the parent id of district
                    contact.Annual_Conference__c = districts.get(contact.District__c).ParentId;
                    
                    // if parent (Jurisdiction) is not null
                    if(districts.get(contact.District__c).Parent.ParentId != null)
                    {
                        // set the jurisdiction
                        contact.Jurisdiction__c = districts.get(contact.District__c).Parent.ParentId;
                    }
                }
            }
            else
            {
                // if annual conference is not null
                if(contact.Annual_Conference__c != null)
                {
                    // set the jurisdiction
                    contact.Jurisdiction__c = annualConferences.get(contact.Annual_Conference__c).ParentId;
                }
            }
        }
    }
    
    /* Raji: 05/13/2011
       Format phone number before insert/update
       Validation rule checks if the format is acceptable
       Raji: 05/17/2011
       Format SSN number before insert/update
       Raji: 07/28/2011
       Salutation Functionality 
     */
    public static void ContactSalutationPhoneSSN(List<Contact> newContacts)
    {
        for (Contact con : newContacts) {
            
            //Phone and SSN
            con.Phone = Util.formatPhone(con.Phone, con.MailingCountry);
            con.Fax = Util.formatPhone(con.Fax, con.MailingCountry);
            con.MobilePhone = Util.formatPhone(con.MobilePhone, con.MailingCountry); 
            con.Emergency_Contact_Number__c= Util.formatPhone(con.Emergency_Contact_Number__c, con.MailingCountry);        
            con.SSN__c = Util.formatSSN(con.SSN__c);
            
            if ((con.Salutation == null ||con.Salutation == 'Missing') && con.Salutation_Other__c == null)
            {
                //Commented out only for migration phase. Rocky Assad 2/1/2012
                //con.Salutation = 'The Rev.';
                //Should Revert back to 'The Rev.',Once migrations are done
                con.Salutation = null;
            }
            else if ((con.Salutation == null||con.Salutation == 'Missing') && con.Salutation_Other__c != null)
            {
                con.Salutation = con.Salutation_Other__c;
                con.Salutation_Other__c = null;
            }
            else if ((con.Salutation != null  ||con.Salutation == 'Missing')&& con.Salutation_Other__c != null)
            {
                con.addError('Salutation Other and First Name : Salutation may not contain values at the same time');
            }
        }
    }
    
    public static void RestrictDistrictType(List<Contact> contacts)
    {   
        // Find all the contacts that have dist super positions
        for(Contact contact : [Select c.Id, (Select Id From Positions__r WHERE Position_Title__c = 'District Superintendent') From Contact c WHERE District__c != null AND c.Id IN :contacts])
        {
            for(Contact con : contacts)
            {
                if(con.Id == contact.Id && !contact.Positions__r.isEmpty())
                {
                    con.District__c.addError('A District Superintendent\'s district is associated with their position. A specific district cannot be associated with a contact record.');
                    break;
                }
            }
        }
    }
    
    public static void ToProperName(List<Contact> newContacts)
    {
        for(Contact contact : newContacts) 
        {
            contact.FirstName = Util.toUpperCase(1, contact.FirstName);
            contact.LastName = Util.toUpperCase(1, contact.LastName);
            contact.Middle_Name__c = Util.toUpperCase(1, contact.Middle_Name__c); 
        }
    }
    
    @future
    public static void ToProperNameAysnc(Set<Id> newContactIds)
    {
        Contact[] contacts = [select Id, FirstName, LastName, Middle_Name__c from Contact where id in :newContactIds];
        
        if(contacts.size() > 0)
        {
            for(Contact contact : contacts) 
            {
                contact.FirstName = Util.toUpperCase(1, contact.FirstName);
                contact.LastName = Util.toUpperCase(1, contact.LastName);
                contact.Middle_Name__c = Util.toUpperCase(1, contact.Middle_Name__c); 
            }
            
            update contacts;
        }
    }
    
    public static void AssociateWithAccount(List<Contact> newContacts)
    {
        Account[] accounts = [SELECT Id FROM Account WHERE Name = 'GBHEM Constituent' limit 1];
        Account account = null;
        
        if(accounts.size() == 0) 
        {
            RecordType recordType = Util.getRecordType('Account', 'Business Account');
            
            account = new Account(Name = 'GBHEM Constituent', RecordTypeId = recordType.Id);
            
            insert account;
        }
        else
        {
            account = accounts[0];
        }
        
        for(Contact contact : newContacts) 
        {   
            contact.AccountId = account.Id;
        }
    }
    
   }