xml/src1/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Programs_offered__c</fullName>
        <description>Programs offered by the schoold</description>
        <label>Programs offered</label>
        <picklist>
            <picklistValues>
                <fullName>A.A.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A.A.S.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A.S.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.A.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.B.A.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.F.A.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.I.S.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.M.E.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.P.A.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S.C.E.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S.E.E.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S.N.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S.W.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D. Min.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ed. D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.A.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.A. in CE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.A. in RE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.A.R.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.A.R.S.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.A.T.S.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.B.A.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.C.E.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M. Div.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M. Ed.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.M.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.R.E.</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Schools</description>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account(School)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>R_Licensing_School__c</fullName>
        <description>For Reports</description>
        <label>R Licensing School</label>
        <length>250</length>
        <type>Text</type>
    </fields>
</CustomObject>

xml/src1/objects/Education_Information__c.object
<CustomObject>
    <description>The type and level of education an individual has received in a particular area.</description>
    <fields>
        <fullName>Education_Detail__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Education Detail</relationshipLabel>
        <relationshipName>Education_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Education_Type__c</fullName>
        <description>A particular group or class of education.</description>
        <inlineHelpText>Select the Education Type that most accurately describes the degree/education experience</inlineHelpText>
        <label>Education Type</label>
        <picklist>
            <picklistValues>
                <fullName>Highest Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undergrad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate/Post Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminary/Theological</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Pastor Licensing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other/Specify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>School</relationshipLabel>
        <relationshipName>Education_Information_Organization</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Education Information</label>
    <nameField>
        <displayFormat>Edu-{00000000}</displayFormat>
        <label>Education ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src1/classes/Handler_Education_Information.cls
public with sharing class Handler_Education_Information
{
    public static void CheckLicensingProgram(List<Education_Information__c> newEducationInfos)
    {
        for(Education_Information__c info : newEducationInfos)
        {
            if(info.Education_Type__c == 'Licensing')
            {
                if(info.School__c != null)
                {
                    Account[] school = [Select Id, Programs_offered__c FROM Account WHERE Id = :info.School__c];
                    
                    if((school[0].Programs_offered__c == null) || (!school[0].Programs_offered__c.contains('Licensing Program')))
                    {
                        info.School__c.addError('Licensing Program not offered for this school');
                    }
                }
            }
        }
    }
    
    public static void CheckForOnlyOneEducationRec(List<Education_Information__c> newEducationInfos)
    {
        Map<id, Education_Information__c> contacts = new Map<id, Education_Information__c>();
        for(Education_Information__c edi : newEducationInfos) 
        {
            contacts.put(edi.Education_Detail__c, edi);
        }
        
        //Highest Education
        Education_Information__c[] existingHighestEd = [SELECT id, Education_Type__c, Education_Detail__c FROM Education_Information__c 
             WHERE Education_Type__c = 'Highest Education' AND Education_Detail__c IN :contacts.keySet()];
        
        // Loop through all records being updated/inserted for Highest education
        for(Education_Information__c edi : newEducationInfos) 
        {
            // Loop through all records being updated/inserted and already have a Highest Education listed
            for(Education_Information__c edi2 : existingHighestEd) 
            {
                // Check if this contact already has a Highest Education record
                if(edi.Education_Detail__c == edi2.Education_Detail__c && 
                   edi.Education_Type__c == 'Highest Education' ) 
                {
                    // Check if they are updating
                    if(edi.id != edi2.id) 
                    {
                        edi.Education_Type__c.addError('Highest Education may only be added once for any given contact');
                    }
                }
            }
        }
            
    }
    //Raji : 11/16/2011
    //Local pastor Licensing
    public static void CheckForOnlyOneEdLocPastorLicensing(List<Education_Information__c> newEducationInfos){
        Map<id, Education_Information__c> contacts = new Map<id, Education_Information__c>();
        for(Education_Information__c EdLocPas : newEducationInfos){
            contacts.put(EdLocPas.Education_Detail__c, EdLocPas);
        }
        Education_Information__c[] existingLocalpastor = [SELECT id, Education_Type__c, Education_Detail__c FROM Education_Information__c 
             WHERE Education_Type__c = 'Local Pastor Licensing' AND Education_Detail__c IN :contacts.keySet()];
        
        // Check if the contact already has a Local Pastor Licensing record
        for(Education_Information__c LocPas : newEducationInfos){
            for(Education_Information__c LocPas2 : existingLocalpastor){
                if(LocPas.Education_Detail__c == LocPas2.Education_Detail__c && LocPas.Education_Type__c == 'Local Pastor Licensing'){
                    if(LocPas.id != LocPas2.id){
                        LocPas.Education_Type__c.addError('Local Pastor Licensing may only be added once for any given contact');
                    } 
                }
            }
        }
            
    }
    //Report Licensing School
    public static void LicensingschoolContactUpdate(List<Education_Information__c> newEducationInfos){
        Set<Id> conIds = new Set<Id>();
        for(Education_Information__c LicEdu : newEducationInfos){
            conIds.add(LicEdu.Education_Detail__c);
        }
        
        Map<Id,contact> contactMap = new Map<Id,Contact>([Select id,R_Licensing_School__c  from contact where Id IN :conIds]);
        Map<Id,Contact> updatedContactMap = new Map<id,Contact>();
        
        //Milestone Age
        for(Education_Information__c LicEdu : newEducationInfos){
            if(LicEdu.Education_Type__c == 'Local Pastor Licensing' && LicEdu.School__c !=null){
                Contact con = contactMap.get(LicEdu.Education_Detail__c);
                con.R_Licensing_School__c = LicEdu.School__c;
                updatedContactMap.put(con.id,con);
            }
        }
        if(updatedContactMap.size() > 0){
            update updatedContactMap.values();
        }
    
    }
    
}