xml/src1/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Schools</description>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account(School)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

xml/src1/objects/Education_Information__c.object
<CustomObject>
    <description>The type and level of education an individual has received in a particular area.</description>
    <fields>
        <fullName>Education_Detail__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Education Detail</relationshipLabel>
        <relationshipName>Education_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Education_Type__c</fullName>
        <description>A particular group or class of education.</description>
        <inlineHelpText>Select the Education Type that most accurately describes the degree/education experience</inlineHelpText>
        <label>Education Type</label>
        <picklist>
            <picklistValues>
                <fullName>Highest Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undergrad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate/Post Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminary/Theological</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Pastor Licensing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other/Specify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>School</relationshipLabel>
        <relationshipName>Education_Information_Organization</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Education Information</label>
    <nameField>
        <displayFormat>Edu-{00000000}</displayFormat>
        <label>Education ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src1/classes/UT_Education_Information_Licensing.cls
@isTest
private class UT_Education_Information_Licensing 
{

    static testMethod void Education_Information_Licensing_School_Single() 
    {
        UnitTest_Exception_Manager.ThrowException = true;
        
        Contact contact = new Contact(Email = 'test@test.com', 
        							  FirstName = 'Rocky', 
        							  LastName = 'Assad_01',
        							  Salutation = 'Mr.');
        							  
        Account[] school = [SELECT Id FROM Account WHERE Name = 'Non-Licensing School'];
        
        if(school.size() == 0)
        {
        	Account act = new Account(Name = 'Non-Licensing School');
        	insert act;
        	
        	school = [SELECT Id FROM Account WHERE Name = 'Non-Licensing School'];
        }
        
        Education_Information__c ed = new Education_Information__c();
        
        insert contact;
        
        ed.Education_Detail__c = contact.Id;
        ed.Education_Type__c = 'Licensing';
        ed.School__c = school[0].Id;
        
        try
        {
        	test.startTest();
        	
        	insert ed;
        }
        catch(DmlException e)
        {
			//Assert Error Message
			System.assert(e.getMessage().contains('Licensing Program not offered for this school'), e.getMessage());
        }
        finally
        {
        	test.stopTest();
        }
    }
}