xml/src1/objects/Account.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>District</description>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District</relationshipLabel>
        <relationshipName>District</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Position Object Lookup object</description>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <description>The default account type.</description>
        <label>Default</label>
    </recordTypes>
    <recordTypes>
        <fullName>District</fullName>
        <active>true</active>
        <description>A grouping of local churches led by a District Superintendent</description>
        <label>District</label>
    </recordTypes>
    <recordTypes>
        <fullName>Jurisdiction</fullName>
        <active>true</active>
        <description>The regional body made up of Annual Conferences</description>
        <label>Jurisdiction</label>
    </recordTypes>
</CustomObject>

xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When a District is selected,Annual Conference and Jurisdiction should select automatically.
The UMC District that the Contact belongs to or where they are serving. The districts in an annual conference varies depends on the size of the Annual conference.Typically 60–80 churches are in a district. Each district is supervised by a district superintendent and Each church or other ministry setting in an annual conference is part of a district.</description>
        <inlineHelpText>Select district where appointed</inlineHelpText>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (District (Organization))</relationshipLabel>
        <relationshipName>District_Members_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

xml/src1/objects/Position__c.object
<CustomObject>
    <description>Positions in Organization Types</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Position the contact is holding</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Position  Organization Name</description>
        <label>Organization Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Position</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position_Title__c</fullName>
        <description>Position in the organizations</description>
        <inlineHelpText>Select title that best describes contact&apos;s position</inlineHelpText>
        <label>Position Title</label>
        <picklist>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant to the President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator/Business Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Discipleship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy/Social Justice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa University Senate Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Conference Treasurer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant District Superintendent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate District Superintendent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Pastor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHECM Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bishop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bishops Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board DHE Vice Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board DOM Vice Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board of Trustees Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Recording Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Co-Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Registrar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Staff Network Position</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Manager of General Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camp Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping &amp; Retreat Ministries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campus Minister</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Superintendent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{00000000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <recordTypes>
        <fullName>District</fullName>
        <active>true</active>
        <description>Positions of the district office</description>
        <label>District</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src1/classes/Handler_Position.cls
public with sharing class Handler_Position 
{
    public static void RemoveDistrictFromContactIfDistSuper(List<Position__c> newPositions)
    {
        Set<Id> contactIds = new Set<Id>();
        List<Contact> contacts = new List<Contact>();
        
        for(Position__c position : newPositions)
        {
            if(position.Position_Title__c == 'District Superintendent')
            {
                contactIds.add(position.Contact__c);
            }
        }
        
        for(Contact contact : [SELECT Id, District__c FROM Contact WHERE District__c != null AND Id IN :contactIds])
        {
            contact.District__c = null;
            contacts.add(contact);
        }
        
        // update contacts
        if(!contacts.isEmpty())
        {
            update contacts;
        }
    }
    
    // Raji : 2/21/2012
    // Rocky Assad : 2/24/2012 (revised)
    //Logic to avoid Lookup Filter Limitation Validation rule
    public static void Pos_LookupFilterValidation(List<Position__c> newPos)
    {
        for(Position__c pos : newPos) 
        {
            if((pos.Organization_Name__c != null) && 
                    ((pos.Organization_Name__r.RecordType.Name != 'Default') || (pos.Organization_Name__r.RecordType.Name != 'Jurisdiction')) &&
                    (pos.RecordType.Name != 'Africa University Board of Directors') &&
                    (pos.RecordType.Name != 'Chaplain Positions') &&
                    (pos.RecordType.Name != 'Connectional Table') && 
                    (pos.RecordType.Name != 'GBHEM Board of Directors') && 
                    (pos.RecordType.Name != 'General Conference') && 
                    (pos.RecordType.Name != 'IAMSCU Board') && 
                    (pos.RecordType.Name != 'NASCUMC Board') && 
                    (pos.RecordType.Name != 'UMHEF Board of Trustees') && 
                    (pos.RecordType.Name != 'University Senate'))
            {
                if((pos.RecordType.Name != pos.Organization_Name__r.RecordType.Name))
                {
                    pos.addError('Organization Record Type should be the same as the position record type.');
                }
            }
        }
    }
}