xml/src1/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Position Object Lookup object</description>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Organization Status</description>
        <label>Organization Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Contact Status</description>
        <inlineHelpText>Select &apos;Inactive&apos; when entire contact record is no longer valid for communication</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

xml/src1/objects/Position__c.object
<CustomObject>
    <description>Positions in Organization Types</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Position the contact is holding</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{00000000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src2/objects/Subscriber__c.object
<CustomObject>
    <description>Subscribers to the Subscription object</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact that will receive this subscription.</description>
        <inlineHelpText>The contact that will receive this subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The organization that will receive this subscription.</description>
        <inlineHelpText>The organization that will receive this subscription.</inlineHelpText>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The position that will receive this subscription.</description>
        <inlineHelpText>The position that will receive this subscription.</inlineHelpText>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Opt In</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Opt Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sticky__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If a subscriber is added manually opposed to being added from a report.</description>
        <inlineHelpText>If a subscriber is added manually opposed to being added from a report.</inlineHelpText>
        <label>Sticky</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>Subscriber-{00000000}</displayFormat>
        <label>Subscriber Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src1/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Mailing_Reports__c</fullName>
        <description>The associated mailing reports that generate the subscribers for this subscription.</description>
        <inlineHelpText>The associated mailing reports that generate the subscribers for this subscription.</inlineHelpText>
        <label>Mailing Reports</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src1/classes/UT_Handler_Subscriber.cls
public with sharing class UT_Handler_Subscriber
{
    private static addSubscribersExtension.SubscriptionManager subscription
    {
        get
        {
            if(subscription == null)
            {
                // contact
                Contact con = new Contact(FirstName = 'Test', LastName = 'Contact');
                insert con ;
                
                // position
                Id posRtId = [SELECT Id FROM RecordType WHERE SObjectType = 'Position__c' AND Name = 'Annual Conference'].Id;
                Position__c pos = new Position__c(RecordTypeId = posRtId, Contact__c = con.Id);
                insert pos;
                
                // organization
                Id accRtId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Annual Conference'].Id;
                Account org = new Account(RecordTypeId = accRtId, Name = 'Test Org');
                insert org;

                Subscription__c subscription_temp = new Subscription__c(Name = 'SubscriptionTesting');
                subscription_temp.Mailing_Reports__c = 'TestReport;';
                insert subscription_temp;
                
                subscription = new addSubscribersExtension.SubscriptionManager(subscription_temp);
                
                List<Subscriber__c> subs = new List<Subscriber__c>();
                Subscriber__c sub1 = new Subscriber__c(Contact__c = con.Id, Status__c = 'Opt In');
                Subscriber__c sub2 = new Subscriber__c(Organization__c = org.Id, Status__c = 'Opt In', Sticky__c = true);
                Subscriber__c sub3 = new Subscriber__c(Position__c = pos.Id, Status__c = 'Opt Out', Sticky__c = true);
                
                sub1.Subscription__c = subscription.subscription.Id;
                sub2.Subscription__c = subscription.subscription.Id;
                sub3.Subscription__c = subscription.subscription.Id;
                
                subs.add(sub1);
                subs.add(sub2);
                subs.add(sub3);
                
                insert subs;
            }
            
            return subscription;
        }
        private set;
    }
    
    static testMethod void checkUniqueSubscriber()
    {
        if(subscription != null)
        {
         //
        }
        
        // contact
        Contact[] con = [SELECT Id FROM Contact WHERE FirstName = 'Test' AND LastName = 'Contact'];
        Account[] org = [SELECT Id FROM Account WHERE Name = 'Test Org'];

        Id posRtId = [SELECT Id FROM RecordType WHERE SObjectType = 'Position__c' AND Name = 'Annual Conference'].Id;
        Position__c[] pos = [SELECT Id FROM Position__c WHERE RecordTypeId = :posRtId LIMIT 1];

        List<Subscriber__c> subs = new List<Subscriber__c>();
        Subscriber__c sub1 = new Subscriber__c(Contact__c = con[0].Id, Status__c = 'Opt In');
        Subscriber__c sub2 = new Subscriber__c(Organization__c = org[0].Id, Status__c = 'Opt In', Sticky__c = true);
        Subscriber__c sub3 = new Subscriber__c(Position__c = pos[0].Id, Status__c = 'Opt Out', Sticky__c = true);
        
        sub1.Subscription__c = subscription.subscription.Id;
        sub2.Subscription__c = subscription.subscription.Id;
        sub3.Subscription__c = subscription.subscription.Id;
        
        
        try
        {
            insert sub1;
        }
        catch(DmlException e)
        {
             System.assert( e.getMessage().contains('Contact already exists in this subscription'), e.getMessage());
        }
        
        try
        {
            insert sub2;
        }
        catch(DmlException e)
        {
             System.assert( e.getMessage().contains('Organization already exists in this subscription'), e.getMessage());
        }
        
        try
        {
            insert sub3;
        }
        catch(DmlException e)
        {
             System.assert( e.getMessage().contains('Position already exists in this subscription'), e.getMessage());
        }
    }
}