xml/src1/objects/Address__c.object
<CustomObject>
    <description>Address of the contacts</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Detail : Addresses of the Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>UNITED STATES OF AMERICA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA &amp; BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOTSWANA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAZIL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Main_Switchboard__c</fullName>
        <inlineHelpText>Enter main phone number on file for the organization here.</inlineHelpText>
        <label>Main/Switchboard</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone of the Contact</description>
        <label>Landline</label>
        <type>Phone</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Address-{00000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SSN__c</fullName>
        <description>Social Security Number</description>
        <inlineHelpText>Enter Contact&apos;s Social Security Number.  May be entered with or without dashes.</inlineHelpText>
        <label>SSN</label>
        <length>11</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

xml/src2/classes/UT_Phone_SSN.cls
/**
 Raji : 08.11.2011
 Test class for SSN& Phone for Contact & Address Functionality .
 */
@isTest
private class UT_Phone_SSN 
{
    static testMethod void UT_Phone_SSN_Contact() 
    {
        UnitTest_Exception_Manager.ThrowException = true;
        
        Contact contact1 = new Contact(
            LastName = 'Last Name',
            Salutation = 'Mr.',
            SSN__c = '234567890',
            Phone = '2345678901',
            MobilePhone = '2345678901',
            MailingCountry =  'UNITED STATES OF AMERICA'
            );
        
        test.startTest();    
        insert contact1;
        Address__c address = new Address__c(
            Contact__c = contact1.Id,
            Main_Switchboard__c = '2345678901',
            Phone__c = '2345678901',
            Mobile__c = '2345678901',
            Country__c = 'UNITED STATES OF AMERICA'
            );
        
        insert address;     
           
        test.stopTest();
        System.debug('contact1' + contact1);
        System.debug('address'+ address); 
        
        Contact contact1record = [SELECT LastName, Salutation, SSN__c, Phone, MobilePhone, MailingCountry FROM Contact WHERE Id =: contact1.Id];
        System.assertEquals('234-56-7890', contact1record.SSN__C);
        //System.assertEquals('(234) 567-8901', contact1record.Phone);
        //System.assertEquals('(234) 567-8901', contact1record.MobilePhone);
        
        Address__c addressrecord = [SELECT Contact__c, Phone__c, Mobile__c, Country__c FROM Address__c WHERE Id =: address.Id];
        System.debug(addressrecord.Phone__c);
        System.debug(addressrecord.Mobile__c);
        
        delete address;
        delete contact1;  
    }
}