xml/src1/objects/Certification_in_Specialized_Ministry__c.object
<CustomObject>
    <description>A listing and details for each certification in specialized ministry that a contact has recevied.</description>
    <fields>
        <fullName>EC_Certification_Renewal_Status__c</fullName>
        <description>For updates from Certification Update</description>
        <label>Certification/Renewal Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Education - Certification</label>
    <nameField>
        <displayFormat>Cert-{00000000}</displayFormat>
        <label>Certification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education - Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src2/objects/Certification_Updates__c.object
<CustomObject>
    <description>Certification Updates for Education Certifications</description>
    <fields>
        <fullName>Certification_Renewal_Status__c</fullName>
        <label>Certification/Renewal Status</label>
        <picklist>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Involuntarily Declined Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reinstated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntarily Declined Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Education_Certification__c</fullName>
        <description>Approving conference for Contact Education Certification</description>
        <label>Education - Certification</label>
        <referenceTo>Certification_in_Specialized_Ministry__c</referenceTo>
        <relationshipName>Renewals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Certification Updates</label>
    <nameField>
        <displayFormat>Certup-{00000000}</displayFormat>
        <label>Certification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certification Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src1/classes/Handler_CertifiedUpdates.cls
/*
Raji : 01/19/2012
Certified Updates : Certified renewal status & Status Functionality for Reports.
*/
public with sharing class Handler_CertifiedUpdates{

  public static void UpdateStatus(List<Certification_Updates__c> newUpdate){  
    for(Certification_Updates__c cu : newUpdate){
        if(cu.Certification_Renewal_Status__c != null){
            if(cu.Certification_Renewal_Status__c == 'Discontinued' || cu.Certification_Renewal_Status__c == 'Involuntarily Declined Renewal'
                        || cu.Certification_Renewal_Status__c == 'Voluntarily Declined Renewal'){
                cu.Status__c = 'InActive';
                }
            if(cu.Certification_Renewal_Status__c == 'Reinstated' || cu.Certification_Renewal_Status__c == 'Renewed'){
                cu.Status__c = 'Active';
                }
            }    
        }
    }
    
    public static void UpdateCertifiedStatus(List<Certification_Updates__c> newCU){
        Set<Id> ecIds = new Set<Id>();
        for(Certification_Updates__c cu : newCU){
            ecIds .add(cu.Education_Certification__c);
        }
        Map<Id,Certification_in_Specialized_Ministry__c> ECMap = new Map<Id,Certification_in_Specialized_Ministry__c>([Select id,EC_Certification_Renewal_Status__c from Certification_in_Specialized_Ministry__c where Id IN :ecIds ]);
        Map<Id,Certification_in_Specialized_Ministry__c> updatedECMap = new Map<id,Certification_in_Specialized_Ministry__c>();
        
        for(Certification_Updates__c cu : newCU)
        {
            if(cu.Certification_Renewal_Status__c != null)
            {
                Certification_in_Specialized_Ministry__c ec = ECMap.get(cu.Education_Certification__c);
                ec.EC_Certification_Renewal_Status__c  = cu.Certification_Renewal_Status__c;
                updatedECMap .put(ec.id,ec);
            }
        }
        if(updatedECMap.size() > 0){
            update updatedECMap.values();
        }
}
}