xml/src1/objects/Certification_in_Specialized_Ministry__c.object
<CustomObject>
    <description>A listing and details for each certification in specialized ministry that a contact has recevied.</description>
    <fields>
        <fullName>Area__c</fullName>
        <inlineHelpText>Select the appropriate area of certification</inlineHelpText>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Business Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping/Retreat Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christian Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evangelism</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ministry with the Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Music Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Older Adult Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spiritual Formation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urban Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Ministry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Certifications_in_Specialized_Ministry</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Track__c</fullName>
        <inlineHelpText>Select the appropriate certification track.  Paraprofessional for contacts working in a specialized area without a Bachelors Degree, Professional for contacts with a Bachelors Degree</inlineHelpText>
        <label>Track</label>
        <picklist>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paraprofessional</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Education - Certification</label>
    <nameField>
        <displayFormat>Cert-{00000000}</displayFormat>
        <label>Certification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education - Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src2/objects/Certification_Updates__c.object
<CustomObject>
    <description>Certification Updates for Education Certifications</description>
    <fields>
        <fullName>Certification_Renewal_Status__c</fullName>
        <label>Certification/Renewal Status</label>
        <picklist>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Involuntarily Declined Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reinstated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntarily Declined Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Education_Certification__c</fullName>
        <description>Approving conference for Contact Education Certification</description>
        <label>Education - Certification</label>
        <referenceTo>Certification_in_Specialized_Ministry__c</referenceTo>
        <relationshipName>Renewals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Certification Updates</label>
    <nameField>
        <displayFormat>Certup-{00000000}</displayFormat>
        <label>Certification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certification Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Contact Status</description>
        <inlineHelpText>Select &apos;Inactive&apos; when entire contact record is no longer valid for communication</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

xml/src1/classes/UT_CertifiedUpdates.cls
/*
Raji : 01/19/2012
Certified Updates : Certified renewal status & Status Functionality for Reports.
*/
@isTest
private class UT_CertifiedUpdates{
    static testMethod void UpdateStatus_test(){
        UnitTest_Exception_Manager.ThrowException = true;
        
        //Insert Contact
        Contact contact1 = new Contact(
            LastName = 'Last Name 1',
            Salutation = 'Mr.'
            );
        test.starttest();
        insert contact1;
        //Education Certification
        Certification_in_Specialized_Ministry__c ec1 = new Certification_in_Specialized_Ministry__c(
            Contact__c = contact1.Id,
            Track__c = 'Professional',
            Area__c = 'Christian Education'
            );
        
        insert ec1;
        // Certification Update
        Certification_Updates__c cu1 = new Certification_Updates__c(
              Education_Certification__c = ec1.Id,
              Certification_Renewal_Status__c = 'Involuntarily Declined Renewal',
              Status__c = 'Active'
              );
        
             
        insert cu1;
        
        Certification_Updates__c cu1record = [SELECT Education_Certification__c, Certification_Renewal_Status__c,Status__c FROM Certification_Updates__c WHERE Id =: cu1.Id];
        System.assertEquals('Inactive', cu1record.Status__c); 
        
        //Update Certified Updates
        Certification_Updates__c cu2 = new Certification_Updates__c(
              Id = cu1.Id,
              Education_Certification__c = ec1.Id,
              Certification_Renewal_Status__c = 'Renewed',
              Status__c = 'InActive'
              );

        Update cu2;
        test.stoptest();
         
         
        Certification_Updates__c cu2record = [SELECT Education_Certification__c, Certification_Renewal_Status__c,Status__c FROM Certification_Updates__c WHERE Id =: cu2.Id];
        System.assertEquals('Active', cu2record.Status__c); 
        


}
}