xml/src1/objects/Global_App_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Store default values for determining runtime behavior.</description>
    <fields>
        <fullName>Developers_Chatter_Group_Default_Member__c</fullName>
        <defaultValue>&quot;rassad.sfadmin@gbhem.org.rocky&quot;</defaultValue>
        <description>The default users email address used to query the user name in this org.</description>
        <inlineHelpText>The default users email address used to query the user name in this org.</inlineHelpText>
        <label>Developers Chatter Group Default Member</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developers_Chatter_Group_Name__c</fullName>
        <defaultValue>&quot;Developers&quot;</defaultValue>
        <description>The name of the chatter group that developers are added to so that they receive system errors as they occur.</description>
        <inlineHelpText>The name of the chatter group that developers are added to so that they receive system errors as they occur.</inlineHelpText>
        <label>Developers Chatter Group Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suppress_Record_Errors_to_Chatter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stops record errors from being posted to the record owners via chatter.</description>
        <inlineHelpText>Stops record errors from being posted to the record owners via chatter.</inlineHelpText>
        <label>Suppress Record Errors to Chatter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Suppress_System_Errors_to_Chatter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stops system errors from being posted to the developers chatter group.</description>
        <inlineHelpText>Stops system errors from being posted to the developers chatter group.</inlineHelpText>
        <label>Suppress System Errors to Chatter</label>
        <type>Checkbox</type>
    </fields>
    <label>Global App Settings</label>
</CustomObject>

xml/src2/objects/System_Execptions__c.object
<CustomObject>
    <description>System exceptions caught and logged via Util_Logging.logSystemErrors method.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Exception description given by Util_Logging.logSystemErrors method</description>
        <inlineHelpText>Exception description given by Util_Logging.logSystemErrors method</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <description>The actual exception thrown by the platform and caught by Util_Logging.logSystemErrors method.</description>
        <inlineHelpText>The actual exception thrown by the platform and caught by Util_Logging.logSystemErrors method.</inlineHelpText>
        <label>Exception</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <description>The record id that caused the exception.</description>
        <inlineHelpText>The record id that caused the exception.</inlineHelpText>
        <label>Record Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>System Execptions</label>
    <nameField>
        <displayFormat>Exception-{00000000}</displayFormat>
        <label>System Exception ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Execptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src1/classes/Util_Logging.cls
global class Util_Logging 
{
    public static Set<Id> NullRecordIds = new Set<Id> { '000000000000000000' };
    
    //@future
    public static void logRecordErrors(Set<Id> recordIds, String msg) 
    {
        // declare local vars
        Global_App_Settings__c appSettings = Global_App_Settings__c.getInstance();
        
        // chatter log
        // post record error to record owners via chatter
        if(!appSettings.Suppress_Record_Errors_to_Chatter__c && appSettings != null)
        {
            List<FeedItem> itemsToCreate = new List<FeedItem>();
            
            for(Id recordId :recordIds) 
            {
                FeedItem post = new FeedItem();
                post.ParentId = recordId;
                post.Body = msg;
                
                itemsToCreate.add(post);
            }
            
            try 
            {
                insert itemsToCreate;
            } 
            catch(DMLException dml) 
            {
                System.debug('an error occurred while creating a chatter post: ' + dml);
            }
        }
    }
    
    //@future
    public static void logSystemErrors(Set<Id> recordIds, String msg, String expMsg) 
    {
        // decalre local vars
        Global_App_Settings__c appSettings = Global_App_Settings__c.getInstance();
        
        // ##########################
        // chatter log
        // ##########################
        
        // check if chatter group exists
        // post record error to record owners via chatter
        if(!appSettings.Suppress_System_Errors_to_Chatter__c && appSettings != null)
        {
            List<FeedItem> itemsToCreate = new List<FeedItem>();
            CollaborationGroup[] collabGroup = [select Id from CollaborationGroup where name = :appSettings.Developers_Chatter_Group_Name__c.trim()];
            Id collabGroupId = null;
            
            if(collabGroup.size() == 0)
            {
                // create chatter group
                CollaborationGroup chatterGroup = new CollaborationGroup(Name = appSettings.Developers_Chatter_Group_Name__c,
                                                                         CollaborationType = 'Private');

                insert chatterGroup;
                
                // add deafult memeber to chatter group
                User defaultMember = [select Id from user where username = :appSettings.Developers_Chatter_Group_Default_Member__c.trim()];
                
                Integer cnt = [select count() from CollaborationGroupMember where CollaborationGroupId = :chatterGroup.Id and MemberId = :defaultMember.Id];
                
                if(cnt == 0)
                {
                    CollaborationGroupMember chatterGroupMember = new CollaborationGroupMember(MemberId = defaultMember.Id,
                                                                                               CollaborationGroupId = chatterGroup.Id);
                
                    insert chatterGroupMember;  
                }
                
                collabGroupId = chatterGroup.Id;
            }
            else
            {
                collabGroupId = collabGroup[0].Id;
            }
            
            for(Id recordId :recordIds) 
            {
                FeedItem post = new FeedItem();
                post.ParentId = collabGroupId;
                post.Body = msg;
                
                itemsToCreate.add(post);
            }
            
            try 
            {
                insert itemsToCreate;
            } 
            catch(DMLException dml) 
            {
                System.debug('an error occurred while creating a chatter post: ' + dml);
            }
        }

        // ##########################
        // system log
        // ##########################
        
        List<System_Execptions__c> exceptions = new List<System_Execptions__c>();
        
        for(Id recordId :recordIds) 
        {
            System_Execptions__c except = new System_Execptions__c();
            
            except.Description__c = msg;
            except.Exception__c = expMsg;
            except.Record_Id__c = String.valueOf(recordId);
            
            exceptions.Add(except);
        }
        
        try 
        {
            insert exceptions;
        } 
        catch(DMLException dml) 
        {
            System.debug('an error occurred while creating a exception log: ' + dml);
        }
    }
}