xml/src1/objects/Position__c.object
<CustomObject>
    <description>Positions in Organization Types</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Position the contact is holding</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{00000000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src2/objects/Subscriber__c.object
<CustomObject>
    <description>Subscribers to the Subscription object</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact that will receive this subscription.</description>
        <inlineHelpText>The contact that will receive this subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The organization that will receive this subscription.</description>
        <inlineHelpText>The organization that will receive this subscription.</inlineHelpText>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The position that will receive this subscription.</description>
        <inlineHelpText>The position that will receive this subscription.</inlineHelpText>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>Subscriber-{00000000}</displayFormat>
        <label>Subscriber Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src1/objects/Subscription__c.object
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src1/classes/Handler_Subscriber.cls
public with sharing class Handler_Subscriber
{
    /* Rocky Assad
       Make sure that subscribers are unique
    */
    public static void checkUniqueSubscriber(List<Subscriber__c> newSubscribers)
    {
        Set<Id> subscriberIds = new Set<Id>();
        Set<Id> subscriptionIds = new Set<Id>();
        
        for(Subscriber__c subscriber : newSubscribers)
        {
            subscriptionIds.add(subscriber.Subscription__c);
            if(subscriber.Contact__c != null)
            {
                subscriberIds.add(subscriber.Contact__c);
                break;
            }
            else if(subscriber.Organization__c != null)
            {
                subscriberIds.add(subscriber.Organization__c);
                break;
            }
            else if(subscriber.Position__c != null)
            {
                subscriberIds.add(subscriber.Position__c);
                break;
            }
        }
        
        for(List<Subscriber__c> extSubs : [SELECT Id, Subscription__c, Contact__c, Organization__c, Position__c FROM Subscriber__c WHERE (Organization__c IN :subscriberIds OR Position__c IN :subscriberIds OR Contact__c IN :subscriberIds) AND Subscription__c IN :subscriptionIds])
        {
            for(Subscriber__c extSub : extSubs)
            {
                Boolean exists = false;
                for(Integer i = 0; i < newSubscribers.size(); i++)
                {
                    if(newSubscribers.get(i).Contact__c != null && 
                       newSubscribers.get(i).Contact__c == extSub.Contact__c && 
                       newSubscribers.get(i).Subscription__c == extSub.Subscription__c)
                    {
                        newSubscribers.get(i).addError('Contact already exists in this subscription.');
                        break;
                    }
                    else if(newSubscribers.get(i).Organization__c != null && 
                            newSubscribers.get(i).Organization__c == extSub.Organization__c && 
                            newSubscribers.get(i).Subscription__c == extSub.Subscription__c)
                    {
                        newSubscribers.get(i).addError('Organization already exists in this subscription.');
                        break;
                    }
                    else if(newSubscribers.get(i).Position__c != null && 
                            newSubscribers.get(i).Position__c == extSub.Position__c && 
                            newSubscribers.get(i).Subscription__c == extSub.Subscription__c)
                    {
                        newSubscribers.get(i).addError('Position already exists in this subscription.');
                        break;
                    }
                }
            }
        }
    }
 }