xml/src1/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Mailing_Reports__c</fullName>
        <description>The associated mailing reports that generate the subscribers for this subscription.</description>
        <inlineHelpText>The associated mailing reports that generate the subscribers for this subscription.</inlineHelpText>
        <label>Mailing Reports</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src2/classes/SubscriptionMaintenance.cls
global class SubscriptionMaintenance implements schedulable
{
    global void execute(SchedulableContext ctx) 
    {
        // setup
        List<Subscription__c> subscriptions = new List<Subscription__c>();
        Map<Id, List<String>> subReports = new Map<Id, List<String>>();
        
        for(Subscription__c subscription : subscriptions)
        {
            String[] reportsDel = subscription.Mailing_Reports__c.split(';', 0);
            List<String> reports = new List<String>();
            
            for(String report : reportsDel )
            {
                reports.add(report.trim());
            }
            
            subReports.put(subscription.Id, reports);
        }
        
        // start working
        for(Subscription__c subb : subscriptions)
        {
           
        }
    } 
}