xml/src2/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Affiliation__c</fullName>
        <description>Affiliation to Schools</description>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>AUMTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BCF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HBCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IAMSCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NASCUMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UM-Related</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>University Senate Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Annual_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Annual Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Annual Conference</relationshipLabel>
        <relationshipName>Annual_Conference</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>District</description>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District</relationshipLabel>
        <relationshipName>District</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Jurisdiction</description>
        <label>Jurisdiction</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jurisdiction</relationshipLabel>
        <relationshipName>Jurisdiction</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>District</fullName>
        <active>true</active>
        <description>A grouping of local churches led by a District Superintendent</description>
        <label>District</label>
    </recordTypes>
    <recordTypes>
        <fullName>Jurisdiction</fullName>
        <active>true</active>
        <description>The regional body made up of Annual Conferences</description>
        <label>Jurisdiction</label>
    </recordTypes>
</CustomObject>

xml/src1/objects/Annual_Conference__c.object
<CustomObject>
    <description>Getting Annual Conferences depending on Episcopal Area</description>
    <fields>
        <fullName>Annual_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organization Annual Conference</description>
        <label>Annual Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Annual Conferences (Annual Conference)</relationshipLabel>
        <relationshipName>Annual</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Conference</label>
    <nameField>
        <displayFormat>AC-{00000000}</displayFormat>
        <label>AC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Conferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Annual_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A geographical area and organization. Defines a region that includes all UM churches and ministries in that area.</description>
        <inlineHelpText>Enter contact&apos;s home annual conference (where membership held)</inlineHelpText>
        <label>Annual Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Appointment_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Most clergy will serve in the annual conference where their membership is held.  However, those in Extension Ministry/ABLC could serve in a different annual conference than where their membership is.Only clergy members should have an assigned Appointment Conference.  The Annual Conference where Contact is appointed to serve.</description>
        <inlineHelpText>If different from Annual Conference, enter annual conference where contact is appointed (working conference)</inlineHelpText>
        <label>Appointment Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Working Conference)</relationshipLabel>
        <relationshipName>Working_Conference</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When a District is selected,Annual Conference and Jurisdiction should select automatically.
The UMC District that the Contact belongs to or where they are serving. The districts in an annual conference varies depends on the size of the Annual conference.Typically 60–80 churches are in a district. Each district is supervised by a district superintendent and Each church or other ministry setting in an annual conference is part of a district.</description>
        <inlineHelpText>Select district where appointed</inlineHelpText>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (District (Organization))</relationshipLabel>
        <relationshipName>District_Members_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Jurisdictions in U.S. (North Central, Northeast, South Central, Southeast, and Western).A group of annual conferences within a geographical region in the United States.</description>
        <inlineHelpText>Auto-populated from annual conference</inlineHelpText>
        <label>Jurisdiction</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jurisdiction</relationshipLabel>
        <relationshipName>Jurisdiction_People</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

xml/src2/classes/UT_AccountUtil.cls
/**
 Raji : 08.09.2011
 Raji Update : 08.10.2011
 1.Test class for Account Util Functionality.
 Raji : 08.10.2011
 2.Test Class for UpdateAccount_AC_JD_District Functionality
 3.Test class for UpdateContact_AC_JD_District_APC for Appoitment conference(trigger).
 4.Test class for UpdateContact_AC_JD_District_APC for Functionality(Class & trigger)
 Infuture if the code is not completely covered : Include one more contact giving value for Annual Conference,
    and check if the Jurisdiction is getting populated. 
 */ 
@isTest
private class UT_AccountUtil {
/*
    static testMethod void AccountUtil_Bulk() 
    {
        UnitTest_Exception_Manager.ThrowException = true;
            
        RecordType rtDistrict = Util.getRecordType('Account', 'District');
        RecordType rtAnnualConference = Util.getRecordType('Account', 'Annual Conference');
        RecordType rtJurisdiction = Util.getRecordType('Account', 'Jurisdiction');
        RecordType rtChurch = Util.getRecordType('Account', 'Local Church');
        
        List<Account> acJurisdictions = new List<Account>();
        
        for(Integer x = 0; x < 200; x++)
        {
            acJurisdictions.Add(new Account(Name = 'Jurisdiction ' + x,
                                            RecordTypeId = rtDistrict.Id));
        }
        
        test.startTest();
        
        insert acJurisdictions;
        update acJurisdictions;
        
        test.stopTest();
        
        // needs test asserts
    }
*/ 
    static testMethod void AccountUtil() 
    {
        UnitTest_Exception_Manager.ThrowException = true;
        
        RecordType AccountSchool = Util.getRecordType('Account', 'Educational Institutions');
        
        Account account1 = new Account(
            Name='Test School 1',
            RecordTypeId = AccountSchool.Id,
            Affiliation__c = 'BCF'
            );
        Account account2 = new Account(
            Name='Test School 2',
            RecordTypeId = AccountSchool.Id,
            Affiliation__c = 'UM-Related'
            );
        Account account3 = new Account(
            Name='Test School 3',
            RecordTypeId = AccountSchool.Id,
            Affiliation__c = 'NASCUMC'
            );
        Account account4 = new Account(
            Name='Test School 4',
            RecordTypeId = AccountSchool.Id,
            Affiliation__c = 'Public;UM-Related'
            );
        test.startTest();
        //System.runAs(u1) {
            insert account1;
            insert account2;
            insert account3;
            try {
                insert account4;
            }
            catch (DmlException e) {
                System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                e.getMessage());
            }
             
        test.stopTest();
          //  }
        Account account1record = [SELECT Name, RecordTypeId, Affiliation__c FROM Account WHERE Id =: account1.Id];
        //System.assertEquals('Private;UM-Related;BCF', account1record.Affiliation__c);
        
        System.assert(account1record.Affiliation__c.contains('BCF'));
        System.assert(account1record.Affiliation__c.contains('UM-Related'));
        System.assert(account1record.Affiliation__c.contains('Private'));
        System.assert(account1record.Affiliation__c.contains('HBCU'));
        String[] parts1 = account1record.Affiliation__c.split(';');
        System.assertEquals(parts1.size(), 4);
                
        Account account2record = [SELECT Name, RecordTypeId, Affiliation__c FROM Account WHERE Id =: account2.Id];
        //System.assertEquals('Private;UM-Related', account2record.Affiliation__c);
        
        System.assert(account2record.Affiliation__c.contains('UM-Related'));
        System.assert(account2record.Affiliation__c.contains('NASCUMC'));
                System.assert(account2record.Affiliation__c.contains('IAMSCU'));

        String[] parts2 = account2record.Affiliation__c.split(';');
        System.assertEquals(parts2.size(), 3);
        
        Account account3record = [SELECT Name, RecordTypeId, Affiliation__c FROM Account WHERE Id =: account3.Id];
        //System.assertEquals('Private;UM-Related;NASCUMC', account3record.Affiliation__c);
        
        System.assert(account3record.Affiliation__c.contains('NASCUMC'));
        System.assert(account3record.Affiliation__c.contains('UM-Related'));
        System.assert(account3record.Affiliation__c.contains('Private'));
        String[] parts3 = account3record.Affiliation__c.split(';');
        System.assertEquals(parts3.size(), 3);
                
        account1.Affiliation__c = 'NASCUMC';
        update account1;
        
        delete account1;
        delete account2;
        delete account3;
                
    }
    
    static testMethod void UpdateAccount_AC_JD_District() 
    {
        UnitTest_Exception_Manager.ThrowException = true;
            
        RecordType rtDistrict = Util.getRecordType('Account', 'District');
        RecordType rtAnnualConference = Util.getRecordType('Account', 'Annual Conference');
        RecordType rtJurisdiction = Util.getRecordType('Account', 'Jurisdiction');
        RecordType rtChurch = Util.getRecordType('Account', 'Local Church');
        
        test.startTest();
        
        Account acJurisdiction = new Account(
            Name = 'Jurisdiction 1',
            RecordTypeId = rtJurisdiction.Id
        );
        insert acJurisdiction;
        
        Account acAnnualConference = new Account(
            Name = 'Annual Conference 1',
            RecordTypeId = rtAnnualConference.Id,
            ParentId = acJurisdiction.Id
        );
        insert acAnnualConference;
        
        Account acDistrict = new Account(
            Name = 'District 1',
            RecordTypeId = rtDistrict.Id,
            ParentId = acAnnualConference.Id
        );
        insert acDistrict;
        
        Account acChurch = new Account(
            Name = 'LocalChurch 1',
            RecordTypeId = rtChurch.Id,
            Annual_Conference__c = acAnnualConference.Id
        );
        insert acChurch;
        
        Contact contact = new Contact(
            LastName = 'Last Name 2',
            Salutation = 'The Rev.',
            District__c = acDistrict.Id
        );
        insert contact;
        
        test.stopTest();
        
        Account account1record = [SELECT Name, RecordTypeId FROM Account WHERE Id = :acJurisdiction.Id];
        Account account2record = [SELECT Name, RecordTypeId, ParentId, Parent.Name  FROM Account WHERE Id = :acAnnualConference.Id];
        // tests?
        
        Account account3record = [SELECT Name, RecordTypeId, ParentId, Parent.Name, Jurisdiction__c  FROM Account WHERE Id = :acDistrict.Id];
        System.assertEquals(account1record.Id, account3record.Jurisdiction__c);
                
        
        Account account4record = [SELECT Name, RecordTypeId, Annual_Conference__c, Jurisdiction__c  FROM Account WHERE Id = :acChurch.Id];
        System.assertEquals(account1record.Id, account4record.Jurisdiction__c);
                
        Contact contact1record = [SELECT LastName, Salutation, District__c, Annual_Conference__c, Jurisdiction__c, Appointment_Conference__c FROM Contact WHERE Id = :contact.Id];
        System.assertEquals(contact1record.Annual_Conference__c, account2record.Id);
        System.assertEquals(contact1record.Jurisdiction__c, account1record.Id);
    }
}