xml/src2/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Organization_Mailing_AddressLine1__c</fullName>
        <description>Organization Street</description>
        <label>Organization Mailing Address Line1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Mailing_Address_Line2__c</fullName>
        <description>Organization Mailing Address Line2 from address</description>
        <label>Organization Mailing Address Line2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Mailing_City__c</fullName>
        <description>Organization Mailing city</description>
        <label>Organization Mailing City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Mailing_Country__c</fullName>
        <description>Organization Country</description>
        <label>Organization Mailing Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Mailing_State__c</fullName>
        <description>Organization Mailing State</description>
        <label>Organization Mailing State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Mailing_Zip_Postal_Code__c</fullName>
        <description>Organization Zip Postal Code</description>
        <label>Organization Mailing Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SearchLayout_City__c</fullName>
        <description>For Search Layouts Of Accounts to Display City on Layouts for the Organizations</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SearchLayout_State__c</fullName>
        <description>For Search Layouts to display state on the layouts for the organization</description>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

xml/src1/objects/Address__c.object
<CustomObject>
    <description>Address of the contacts</description>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <description>Street address of the contacts</description>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line2__c</fullName>
        <description>Address Line 2</description>
        <inlineHelpText>Enter campus boxes, apartment numbers, and other secondary address data here to simplify Address Line 1.</inlineHelpText>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alternate_Phone__c</fullName>
        <description>Alternate Phone other than the Landline</description>
        <inlineHelpText>Enter valid secondary phone number here, if applicable.</inlineHelpText>
        <label>Alternate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Address : City</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>UNITED STATES OF AMERICA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA &amp; BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOTSWANA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAZIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Main_Switchboard__c</fullName>
        <inlineHelpText>Enter main phone number on file for the organization here.</inlineHelpText>
        <label>Main/Switchboard</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If an Organization exists,elect it here.  Otherwise, enter the name in the Address Name text field.</description>
        <label>Organization Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone of the Contact</description>
        <label>Landline</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State_Other__c</fullName>
        <inlineHelpText>Enter non-US state name here when &apos;Other/Specify&apos; is selected</inlineHelpText>
        <label>State Other</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>States in USA &amp; Canada</description>
        <label>State/Province</label>
        <picklist>
            <controllingField>Country__c</controllingField>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Address-{00000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src2/classes/Handler_Address.cls
/* Raji: 05/13/2011
       Format phone number before insert/update
       Validation rule checks if the format is acceptable:Shld talk to rebecca for brazil.
       Raji : 12.09.2011
       Functionality : Organization mailing address For Reports
       Search Layouts : City & State on all Search Layouts
    */
public with sharing class Handler_Address{
    public static void FormatPhone(List<Address__c> newAddresses){
        for (Address__c address : newAddresses){
            address.Main_Switchboard__c = Util.formatPhone(address.Main_Switchboard__c, address.Country__c);
            address.Phone__c = Util.formatPhone(address.Phone__c, address.Country__c);
            address.Mobile__c = Util.formatPhone(address.Mobile__c, address.Country__c);
            address.Fax__c = Util.formatPhone(address.Fax__c , address.Country__c);
            address.Alternate_Phone__c = Util.formatPhone(address.Alternate_Phone__c, address.Country__c);
            address.Zip_Postal_Code__c =Util.formatPC(address.Zip_Postal_Code__c); 
            
                               
        }
             
    }
    //Reports to get Organization MAiling Address
    public static void ReportsOrgMailingAddress(List<Address__c> newAddresses){
        RecordType OrgMail = Util.getRecordType('Address__c', 'Organization Mailing');
        RecordType OrgLoc = Util.getRecordType('Address__c', 'Organization Location');
        
        Set<Id> OrgIds = new Set<Id>();
        for(Address__c address : newAddresses){
            OrgIds.add(address.Organization_Name__c);
        }
        Map<Id,Account> OrgMap = new Map<Id,Account>([Select id, Organization_Mailing_City__c,
                Organization_Mailing_Country__c,Organization_Mailing_State__c,Organization_Mailing_AddressLine1__c,Organization_Mailing_Address_Line2__c  ,Organization_Mailing_Zip_Postal_Code__c,
                SearchLayout_City__c,SearchLayout_State__c from Account where Id IN :OrgIds]);
        Map<Id,Account> updatedOrgMap = new Map<id,Account>();
        
        //address Organization Mailing Address
        for(Address__c address : newAddresses){
                              
            //City & State on all Search Layouts
            if(address.RecordTypeId == OrgLoc.Id){
                Account Org = OrgMap.get(address.Organization_Name__c);
                Org.SearchLayout_City__c = address.City__c;
                Org.SearchLayout_State__c = address.State__c;
                updatedOrgMap.put(Org.id,Org);
            }
            //Organization Mailing Address
            if(address.RecordTypeId == OrgMail.Id){
                Account Org = OrgMap.get(address.Organization_Name__c);
                //For United states of America & Canada
                if(address.Country__c == 'UNITED STATES OF AMERICA' || address.Country__c == 'CANADA'){
                    //Address Line 1 & Address Line 2
                    if (address.Address_Line1__c != null){Org.Organization_Mailing_AddressLine1__c = address.Address_Line1__c;}
                    if (address.Address_Line2__c != null){Org.Organization_Mailing_Address_Line2__c = address.Address_Line2__c;}
                    If(address.City__c !=null){Org.Organization_Mailing_City__c = address.City__c;}                    
                    If(address.State__c !=null){Org.Organization_Mailing_State__c = address.State__c;}
                    If(address.Zip_Postal_Code__c!=null){Org.Organization_Mailing_Zip_Postal_Code__c = address.Zip_Postal_Code__c;}
                    }//Countries are USA & Canada
                //If Countries are not Unites States of America & Canada
                else if(address.Country__c != 'UNITED STATES OF AMERICA' || address.Country__c != 'CANADA'){
                    
                    //Address Line 1 & Address Line 2
                    if (address.Address_Line1__c != null){Org.Organization_Mailing_AddressLine1__c= address.Address_Line1__c;}
                    if (address.Address_Line2__c != null){Org.Organization_Mailing_Address_Line2__c = address.Address_Line2__c;}
                    If(address.City__c !=null){Org.Organization_Mailing_City__c = address.City__c;}
                    If(address.State_Other__c !=null){Org.Organization_Mailing_State__c = address.State_Other__c;}
                    If(address.Zip_Postal_Code__c!=null){Org.Organization_Mailing_Zip_Postal_Code__c = address.Zip_Postal_Code__c;}
                    If(address.Country__c!=null){Org.Organization_Mailing_Country__c = address.Country__c;}
                    }//Countries are not USA & CANADA
                updatedOrgMap.put(Org.id,Org);
            }
            
        }
        if(updatedOrgMap.size() > 0){
            update updatedOrgMap.values();
        }
    }
    
        
}