xml/src2/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Organization Status</description>
        <label>Organization Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

xml/src1/objects/Address__c.object
<CustomObject>
    <description>Address of the contacts</description>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <description>Street address of the contacts</description>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line2__c</fullName>
        <description>Address Line 2</description>
        <inlineHelpText>Enter campus boxes, apartment numbers, and other secondary address data here to simplify Address Line 1.</inlineHelpText>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Address : City</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confidential_Mailing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Mailing address that should be used for confidentiality.</description>
        <inlineHelpText>Select if postal address is OCAS-related or is contact&apos;s desired address to receive confidential mailings</inlineHelpText>
        <label>Confidential Mailing Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Detail : Addresses of the Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>UNITED STATES OF AMERICA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA &amp; BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOTSWANA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAZIL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_Confidential_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Email should be used for the Confidentiality</description>
        <inlineHelpText>Select if address is OCAS-related or is contact&apos;s desired location to receive confidential email</inlineHelpText>
        <label>Email Confidential Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the Contact</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date of the address</description>
        <inlineHelpText>Enter date only when address is known to be incorrect or &apos;outdated&apos;</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Main_Switchboard__c</fullName>
        <inlineHelpText>Enter main phone number on file for the organization here.</inlineHelpText>
        <label>Main/Switchboard</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone_Extension__c</fullName>
        <description>Phone Extension</description>
        <label>Landline Extension</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone of the Contact</description>
        <label>Landline</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Email_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primarary address of the Contact</description>
        <label>Primary Email Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Mailing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primary Mailing address of the contact</description>
        <inlineHelpText>Select one address to send postal mail</inlineHelpText>
        <label>Primary Mailing Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date of the Address</description>
        <inlineHelpText>Date that contact will begin residing at this address</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State_Other__c</fullName>
        <inlineHelpText>Enter non-US state name here when &apos;Other/Specify&apos; is selected</inlineHelpText>
        <label>State Other</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>States in USA &amp; Canada</description>
        <label>State/Province</label>
        <picklist>
            <controllingField>Country__c</controllingField>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other/Specify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Address Type</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>URL of the person web address,or the Person company address</description>
        <inlineHelpText>Enter only personal website address for this contact</inlineHelpText>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Address-{00000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Address_Line1__c</fullName>
        <description>Contact address Line 1 From Address</description>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Address_Line2__c</fullName>
        <description>Contact address Line 2 from address</description>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_City__c</fullName>
        <description>Contact city from Address city</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_State__c</fullName>
        <description>Contact State from Address State or State other</description>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Extension__c</fullName>
        <description>Phone Extension</description>
        <label>Phone Extension</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Contact Status</description>
        <inlineHelpText>Select &apos;Inactive&apos; when entire contact record is no longer valid for communication</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>Url of the Contacts organization or his own .</description>
        <label>URL</label>
        <type>Url</type>
    </fields>
</CustomObject>

xml/src2/classes/UT_Address.cls
/**
 Raji : 08.11.2011
 1.Test class for Address Trigger Functionality.
 */
@isTest
private class UT_Address {
  
    static testMethod void UT_Address_insert() {
        RecordType addressHome = Util.getRecordType('Address__c', 'Contact  Home Address');
        RecordType addressSchool = Util.getRecordType('Address__c', 'Contact School Address');
        RecordType addressMilitary = Util.getRecordType('Address__c', 'Contact Military Address');
        
        Contact contact1 = new Contact(
            LastName = 'Last Name',
            Salutation = 'Mr.'
            );
        
        Contact contact2 = new Contact(
            LastName = 'Last Name2',
            Salutation = 'Mr.'
            );
        
        test.startTest();
        insert contact1;
        insert contact2;
        
        Address__c address1 = new Address__c(
            RecordTypeId = addressHome.Id,
            Contact__c = contact1.Id,
            Primary_Mailing_Address__c = true,
            Confidential_Mailing_Address__c = true,
            Address_Line1__c = 'Address Line 1',
            Address_Line2__c = 'Address Line 2',
            City__c = 'City 1',
            State__c = 'NY',
            Country__c = 'UNITED STATES OF AMERICA',
            Primary_Email_Address__c = true,
            Email_Confidential_Only__c = true,
            Email__c = 'email1@test.com',
            //Primary_Phone__c = 'Landline',
            Phone__c = '1234567890',
            Mobile__c = '2345671234',
            Phone_Extension__c = '2345',
            URL__C = 'www.test.com',
            Fax__c = '1234567890'
            );
                        
        insert address1;
        
        Address__c address2 = new Address__c(
            RecordTypeId = addressSchool.Id,
            Contact__c = contact1.Id,
            Primary_Mailing_Address__c = true,
            Address_Line1__c = 'Address Line 1',
            Address_Line2__c = 'Address Line 2',
            City__c = 'City 1',
            State__c = 'Other/Specify',
            State_Other__c = 'State test',
            Country__c = 'ARGENTINA'
            );
                        
        try{
            insert address2;
            }
        catch (DmlException e){
            System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                    e.getMessage());
            }
            
        Address__c address2a = new Address__c(
            RecordTypeId = addressSchool.Id,
            Contact__c = contact1.Id,
            Confidential_Mailing_Address__c = true,
            Address_Line1__c = 'Address Line 1',
            Address_Line2__c = 'Address Line 2',
            City__c = 'City 1',
            State__c = 'NY',
            Country__c = 'UNITED STATES OF AMERICA'
            );
                        
        try{
            insert address2a;
            }
        catch (DmlException e){
            System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                    e.getMessage());
            }
        
        Address__c address3 = new Address__c(
            RecordTypeId = addressSchool.Id,
            Contact__c = contact1.Id,
            Primary_Email_Address__c = true,
            Email__c = 'email1@test.com'
            );
                        
        try{
            insert address3;
            }
        catch (DmlException e){
            System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                    e.getMessage());
            }
        
        Address__c address3a = new Address__c(
            RecordTypeId = addressSchool.Id,
            Contact__c = contact1.Id,
            Email_Confidential_Only__c = true,
            Email__c = 'email1@test.com'
            );
                        
        try{
            insert address3a;
            }
        catch (DmlException e){
            System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                    e.getMessage());
            }
            
        Address__c address4 = new Address__c(
            RecordTypeId = addressSchool.Id,
            Contact__c = contact1.Id,
            //Primary_Phone__c = 'Landline',
            Phone__c = '1234567890'
            );
                        
        try{
            insert address4;
            }
        catch (DmlException e){
            System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                    e.getMessage());
            }
        
        Address__c address5 = new Address__c(
            RecordTypeId = addressMilitary.Id,
            Contact__c = contact2.Id,
            Primary_Mailing_Address__c = true,
            Address_Line1__c = 'Address Line 1',
            Address_Line2__c = 'Address Line 2',
            City__c = 'City 1',
            State__c = 'Other/Specify',
            State_Other__c = 'State test',
            Country__c = 'ARGENTINA'
            );
        
        insert address5;
        
        test.stopTest();
        Address__c Address1Record = [SELECT Mobile__c,Phone__c,URL__c, Email__c FROM Address__c WHERE Id =: address1.Id];
        
        Contact contact1record = [SELECT LastName, Salutation, Phone,Phone_Extension__c, MobilePhone, 
            Contact_Address_Line1__c, Contact_Address_Line2__c, Contact_State__c, Contact_Country__c, Contact_City__c, URL__c, Fax, Email FROM Contact WHERE Id =: contact1.Id];
        System.assertEquals(address1.City__c, contact1record.Contact_City__c);
        System.debug(contact1record.Contact_Address_Line1__c);
        System.debug(contact1record.Phone);
        System.debug(contact1record.Phone_Extension__c);
        System.debug(contact1record.Contact_State__c);
        System.debug(contact1record.Contact_Country__c);
        System.assertEquals(address1.Email__C, contact1record.Email);
        System.debug(contact1record.Fax);
        System.assertEquals(address1.URL__c, contact1record.URL__c);
        
        Contact contact2record = [SELECT LastName, Salutation, 
            Contact_Address_Line1__c, Contact_Address_Line2__c, Contact_State__c, Contact_Country__c, Contact_City__c FROM Contact WHERE Id =: contact2.Id];     
      Address__c Address2Record = [SELECT Mobile__c,Phone__c,URL__c, Email__c FROM Address__c WHERE Id =: address5.Id]; 
       System.debug(contact2record.Contact_Address_Line1__c);
      System.debug(contact2record.Contact_State__c);
      System.debug(contact2record.Contact_Country__c);
      System.debug(contact2record.Contact_Address_Line2__c);
        
        
        
        delete address5;
        delete address1;
        //delete address6;
        delete contact1;
        delete contact2;
    
    }
    
    static testMethod void UT_Address_update() {
    
        RecordType addressHome = Util.getRecordType('Address__c', 'Contact  Home Address');
        RecordType addressSchool = Util.getRecordType('Address__c', 'Contact School Address');
        Contact contact1 = new Contact(
            LastName = 'Last Name',
            Salutation = 'Mr.'
            );
        
        test.startTest();
        insert contact1;
        Address__c address1 = new Address__c(
            //Id = address1.Id,
            RecordTypeId = addressHome.Id,
            Contact__c = contact1.Id,
            Primary_Mailing_Address__c = true,
            Address_Line1__c = 'Address Line 1',
            Address_Line2__c = 'Address Line 2',
            City__c = 'City 1',
            State__c = 'NY',
            Country__c = 'UNITED STATES OF AMERICA',
            Primary_Email_Address__c = true,
            Email__c = 'email1@test.com',
            //Primary_Phone__c = 'Mobile',
            Mobile__c = '1234567890',
            Start_Date__c = Date.valueOf('2010-08-10') 
            );
                        
        insert address1;
        Contact contactrecord = [SELECT LastName, Salutation, Phone, MobilePhone, 
            Contact_Address_Line1__c, Contact_Address_Line2__c, Contact_State__c, Contact_Country__c, Contact_City__c,Email FROM Contact WHERE Id =: contact1.Id];
            
        System.assertEquals(address1.Main_Switchboard__c, contactrecord.Phone);
        //System.assertEquals(address1.Mobile__c, contactrecord.MobilePhone);
        
        Address__c address3 = new Address__c(
            RecordTypeId = addressHome.Id,
            Contact__c = contact1.Id,
            //Primary_Phone__c = 'Mobile',
            Mobile__c = '1234567890'
            );
                        
        try{
            insert address3;
            }
        catch (DmlException e){
            System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                    e.getMessage());
            }
        
        Address__c address4 = new Address__c(
            RecordTypeId = addressSchool.Id,
            Contact__c = contact1.Id,
            //Primary_Phone__c = 'Mobile',
            Mobile__c = '123456789'
            );
                        
        try{
            insert address4;
            }
        catch (DmlException e){
            System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                    e.getMessage());
            }
        Address__c address2 = new Address__c(
            Id = address1.Id,
            RecordTypeId = addressHome.Id,
            Contact__c = contact1.Id,
            Primary_Mailing_Address__c = false,
            Address_Line1__c = 'Address Line 1',
            Address_Line2__c = 'Address Line 2',
            City__c = 'City 1',
            State__c = 'NY',
            Country__c = 'UNITED STATES OF AMERICA',
            Primary_Email_Address__c = false,
            Email__c = 'email1@test.com',
            //Primary_Phone__c = 'Landline',
            Phone__c = '2345678999',
            //Phone_Extension__c = '2345',
            End_Date__c = Date.today() 
            );
                        
        update address2;
        
        //Update NON USA & Canada
        
        Address__c addressNONUSA = new Address__c(
            //Id = address1.Id,
            RecordTypeId = addressHome.Id,
            Contact__c = contact1.Id,
            Primary_Mailing_Address__c = true,
            Address_Line1__c = 'Address Line 1',
            Address_Line2__c = 'Address Line 2',
            City__c = 'City 1',
            State__c = 'Other/Specify',
            State_Other__c = 'State test',
            Country__c = 'ARGENTINA',
            //Primary_Email_Address__c = true,
            Email__c = 'email1@test.com',
            //Primary_Phone__c = 'Mobile',
            Mobile__c = '1234567890',
            Start_Date__c = Date.valueOf('2010-08-10') 
            );
                        
        insert addressNONUSA ;
        
        Address__c addressNONUSAUpdate = new Address__c(
            Id = addressNONUSA.Id,
            RecordTypeId = addressHome.Id,
            Contact__c = contact1.Id,
            Address_Line1__c = 'Address Line 1 NON USA',
            Address_Line2__c = 'Address Line 2 NON USA',
            City__c = 'City 1 NON USA',
            State__c = 'Other/Specify',
            State_Other__c = 'State test NON USA',
            Country__c = 'ARGENTINA',
            Email__c = 'email1@test.com'
            );
                        
        Update addressNONUSAUpdate;
        
        test.stopTest();
        
        Contact contact1record = [SELECT LastName, Salutation, Phone, MobilePhone,Phone_Extension__c, 
            Contact_Address_Line1__c, Contact_Address_Line2__c,Contact_State__c, Contact_Country__c, Contact_City__c,Email FROM Contact WHERE Id =: contact1.Id];
        
        System.assertNotEquals(address2.City__c, contact1record.Contact_City__c);
        System.debug(contact1record.Contact_Address_Line1__c);
        System.assertNotEquals(address2.City__c, contact1record.Contact_City__c);
        System.debug('contact1record.Phone :'+contact1record.Phone);
        System.debug('contact1record.MobilePhone :'+contact1record.MobilePhone);
        System.debug('contact1record.Phone_Extension__c :'+contact1record.Phone_Extension__c);
        System.assertNotEquals(address2.State__c, contact1record.Contact_State__c);
        System.assertNotEquals(address2.Country__c, contact1record.Contact_Country__c);
        System.assertNotEquals(address2.Email__C, contact1record.Email);
       
        Address__c addressrecord = [SELECT Contact__c, Phone__c,Status__c, End_Date__c FROM Address__c WHERE Id =: address2.Id];
        System.assertEquals('Inactive', addressrecord.Status__c);
       
        // For Not USA & Canada
        Address__c address1record = [SELECT Contact__c, Phone__c,Status__c, End_Date__c FROM Address__c WHERE Id =: addressNONUSAUpdate.Id];
        System.debug(contact1record.Contact_State__c);
        System.debug(contact1record.Contact_Country__c);
        System.debug(contact1record.Contact_City__c);
        
        delete address2;
        //delete address1;
        delete contact1;
        
    }
    //Test for Organization mailing Address & Organization Location Updates
    static testMethod void UT_Address_update_Organization() {
    
    RecordType OrgMail = Util.getRecordType('Address__c', 'Organization Mailing');
    RecordType OrgLoc = Util.getRecordType('Address__c', 'Organization Location');
    RecordType AccountSchool = Util.getRecordType('Account', 'Educational Institutions');
    
    Account account1 = new Account(
            Name='Test School 1',
            RecordTypeId = AccountSchool.Id,
            Affiliation__c = 'BCF'
            );
    Address__c address1 = new Address__c(
            RecordTypeId = OrgMail.Id,
            Organization_Name__c = account1.Id,
            Address_Line1__c = 'Address Line 1',
            Address_Line2__c = 'Address Line 2',
            City__c = 'City 1',
            State__c = 'NY',
            Country__c = 'UNITED STATES OF AMERICA',
            //Primary_Phone__c = 'Landline',
            Main_Switchboard__c = '2345678999',
            //Phone_Extension__c = '2345',
            End_Date__c = Date.today() 
            );  
    Address__c addressmailing = new Address__c(
            Id = address1.Id,
            RecordTypeId = OrgMail.Id,
            Organization_Name__c = account1.Id,
            Address_Line1__c = 'Address Line 1 mailing',
            Address_Line2__c = 'Address Line 2 ',
            City__c = 'City 1',
            State__c = 'NY',
            Country__c = 'UNITED STATES OF AMERICA',
            //Primary_Phone__c = 'Landline',
            Main_Switchboard__c = '2345678999',
            //Phone_Extension__c = '2345',
            End_Date__c = Date.today() 
            );  
            
    Address__c address2 = new Address__c(
            RecordTypeId = OrgMail.Id,
            Organization_Name__c = account1.Id,
            Address_Line1__c = 'Address Line 1',
            Address_Line2__c = 'Address Line 2',
            City__c = 'City 1',
            State__c = 'Other/Specify',
            State_Other__c = 'State test',
            Country__c = 'ARGENTINA',
            //Primary_Phone__c = 'Landline',
            Main_Switchboard__c = '2345678999',
            Phone_Extension__c = '2345',
            Alternate_Phone__c = '1234567812',
            End_Date__c = Date.today() 
            );  
    Address__c address3 = new Address__c(
            Id = address2.Id,
            RecordTypeId = OrgMail.Id,
            Organization_Name__c = account1.Id,
            Address_Line1__c = 'Address Line 1non',
            Address_Line2__c = 'Address Line 2non',
            City__c = 'City 1Update',
            State__c = 'Other/Specify',
            State_Other__c = 'State test update',
            Country__c = 'ARGENTINA',
            Alternate_Phone__c = '1236767812',
            Main_Switchboard__c = '2345678444'
            );
     //Organization Loc State & City
     Address__c address3LOC = new Address__c(
            //Id = address2.Id,
            RecordTypeId = OrgLoc.Id,
            Organization_Name__c = account1.Id,
            Address_Line1__c = 'Address Line 1loc',
            City__c = 'City 1',
            State__c = 'NY',
            Country__c = 'UNITED STATES OF AMERICA',
            Alternate_Phone__c = '1236767812',
            Main_Switchboard__c = '2345678444'
            );
            
    test.startTest();
    insert account1;
    insert address1;
    
     Account accountrecord = [Select id, Organization_Mailing_Country__c, Organization_Mailing_City__c, 
        Organization_Mailing_State__c, SearchLayout_City__c,Organization_Mailing_AddressLine1__c ,
        Organization_Mailing_Address_Line2__c , 
        Organization_Mailing_Zip_Postal_Code__c, SearchLayout_State__c from Account WHERE Id =: account1.Id];
    Address__c addresMailingsrecord = [SELECT City__c,State__c,Organization_Name__c FROM Address__c WHERE Id =: address1.Id];
    System.debug('Organization_Mailing_AddressLine1__c :' + accountrecord .Organization_Mailing_AddressLine1__c );
    System.debug('Organization_Mailing_Address_Line2__c :' + accountrecord .Organization_Mailing_Address_Line2__c );
    System.debug('Organization_Mailing_Country__c:' + accountrecord .Organization_Mailing_Country__c);
    System.debug('Organization_Mailing_City__c:' + accountrecord .Organization_Mailing_City__c);
    System.debug('Organization_Mailing_State__c:' + accountrecord .Organization_Mailing_State__c);
    System.debug('Organization_Mailing_Country__c:' + accountrecord .Organization_Mailing_Country__c); 
    insert addressmailing;
    Address__c addresMailing1srecord = [SELECT City__c,State__c,Organization_Name__c FROM Address__c WHERE Id =: address1.Id];
    System.debug('Organization_Mailing_AddressLine1__c :' + accountrecord .Organization_Mailing_AddressLine1__c );
    System.debug('Organization_Mailing_Address_Line2__c :' + accountrecord .Organization_Mailing_Address_Line2__c );
    System.debug('Organization_Mailing_Country__c:' + accountrecord .Organization_Mailing_Country__c);
    
    insert address2;
    insert address3;
    insert address3LOC ;
    test.stopTest();
    
    Account account1record = [Select id, Organization_Mailing_Country__c, Organization_Mailing_City__c, 
        Organization_Mailing_State__c, SearchLayout_City__c, Organization_Mailing_AddressLine1__c ,
        Organization_Mailing_Address_Line2__c , 
        Organization_Mailing_Zip_Postal_Code__c, SearchLayout_State__c from Account WHERE Id =: account1.Id];
    
    Address__c addressrecord = [SELECT City__c,State__c,Organization_Name__c FROM Address__c WHERE Id =: address2.Id];
    System.debug('Organization_Mailing_AddressLine1__c :' + accountrecord .Organization_Mailing_AddressLine1__c );
    System.debug('Organization_Mailing_Address_Line2__c :' + accountrecord .Organization_Mailing_Address_Line2__c );
    System.debug('Organization_Mailing_Country__c:' + accountrecord .Organization_Mailing_Country__c);
   
    Address__c address1record = [SELECT City__c,State__c,Organization_Name__c FROM Address__c WHERE Id =: address3LOC.Id];
    System.debug('SearchLayout_City__c :' + account1record.SearchLayout_City__c); 
    System.debug('SearchLayout_State__c :' + account1record.SearchLayout_State__c); 
        
    delete address1;
    delete address2;
    delete address3;
    delete account1;    
    
    }
}