xml/src2/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Affiliation__c</fullName>
        <description>Affiliation to Schools</description>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>AUMTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BCF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HBCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IAMSCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NASCUMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UM-Related</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>University Senate Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>District</description>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District</relationshipLabel>
        <relationshipName>District</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Position Object Lookup object</description>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>District</fullName>
        <active>true</active>
        <description>A grouping of local churches led by a District Superintendent</description>
        <label>District</label>
    </recordTypes>
</CustomObject>

xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When a District is selected,Annual Conference and Jurisdiction should select automatically.
The UMC District that the Contact belongs to or where they are serving. The districts in an annual conference varies depends on the size of the Annual conference.Typically 60–80 churches are in a district. Each district is supervised by a district superintendent and Each church or other ministry setting in an annual conference is part of a district.</description>
        <inlineHelpText>Select district where appointed</inlineHelpText>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (District (Organization))</relationshipLabel>
        <relationshipName>District_Members_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

xml/src1/objects/Position__c.object
<CustomObject>
    <description>Positions in Organization Types</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Position the contact is holding</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Position  Organization Name</description>
        <label>Organization Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Position</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position_Title__c</fullName>
        <description>Position in the organizations</description>
        <inlineHelpText>Select title that best describes contact&apos;s position</inlineHelpText>
        <label>Position Title</label>
        <picklist>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant to the President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator/Business Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Discipleship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy/Social Justice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa University Senate Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Conference Treasurer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant District Superintendent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate District Superintendent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Pastor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHECM Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bishop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bishops Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board DHE Vice Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board DOM Vice Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board of Trustees Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Recording Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Co-Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Registrar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Staff Network Position</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Manager of General Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camp Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping &amp; Retreat Ministries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campus Minister</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Superintendent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>Position-{00000000}</displayFormat>
        <label>Position ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <recordTypes>
        <fullName>District</fullName>
        <active>true</active>
        <description>Positions of the district office</description>
        <label>District</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src2/classes/UT_Position.cls
@isTest
private class UT_Position 
{
    static Contact contact = null;
    
    static testMethod void TestInsertDistSuper() 
    {
        UnitTest_Exception_Manager.ThrowException = true;
        
        test.startTest();
        InitContact();
        
        Id dsRt = [SELECT Id FROM RecordType WHERE Name = 'District' AND SObjectType = 'Position__c'].Id;
        
        // Try to insert a new district superintendent position for a contact with a district
        Position__c dsPosition = new Position__c(Contact__c = contact.Id, RecordTypeId = dsRt, Position_Title__c = 'District Superintendent');
        
        System.assertNotEquals(null, contact.District__c);
        test.stopTest();
        
        insert dsPosition;
        
        contact = [SELECT Id, District__c FROM Contact WHERE Id = :contact.Id];
        
        System.assertEquals(null, contact.District__c);
    }
    
    static testMethod void TestUpdateDistSuper() 
    {
        UnitTest_Exception_Manager.ThrowException = true;
        
        test.startTest();
        InitContact();
        
        Id dsRt = [SELECT Id FROM RecordType WHERE Name = 'District' AND SObjectType = 'Position__c'].Id;
        
        // Try to insert a new district superintendent position for a contact with a district
        Position__c dsPosition = new Position__c(Contact__c = contact.Id, RecordTypeId = dsRt, Position_Title__c = 'Missing');
        
        insert dsPosition;
        
        System.assertNotEquals(null, contact.District__c);
        
        dsPosition.Position_Title__c = 'District Superintendent';
        test.stopTest();
        
        update dsPosition;
        
        contact = [SELECT Id, District__c FROM Contact WHERE Id = :contact.Id];
        
        System.assertEquals(null, contact.District__c);
    }
    
    private static void InitContact()
    {
        Id rt = [SELECT Id FROM RecordType WHERE Name = 'District' AND SObjectType = 'Account'].Id;
        Account district = new Account(RecordTypeId = rt, Name = 'Test District Test');
        
        insert district;
        
        contact = new Contact(FirstName = 'Position Test', LastName = 'Tester', District__c = district.Id);
        
        insert contact;
    } 
    
     //Raji : 2/22/2012
    //Logic to avoid Lookup Filter Limitation Validation rule testing
    static testMethod void position_OrgLookupFilter(){
        UnitTest_Exception_Manager.ThrowException = true;
        
        //record types
        RecordType RT_AC = Util.getRecordType('Account', 'Annual Conference');
        RecordType RT_CM = Util.getRecordType('Account', 'Collegiate Ministry');
        RecordType RT_D = Util.getRecordType('Account', 'District');
        RecordType RT_EI = Util.getRecordType('Account', 'Educational Institutions');

        Account org_EI = new Account(
            Name='Test School 1',
            RecordTypeId = RT_EI.Id,
            Affiliation__c = 'BCF'
            );
                                      
        insert org_EI ;
        Account org_AC = new Account(
            Name='Test AC 1',
            RecordTypeId = RT_AC.Id
           );
                                      
        insert org_AC ;
        Account org_CM = new Account(
            Name='Test CM 1',
            RecordTypeId = RT_CM.Id
           );
                                      
        insert org_CM ;
        
        Contact con = new Contact(
            LastName = 'Last Name 2',
            Salutation = 'The Rev.'
         );
        insert con;
    
        //Position
        RecordType RT_AC_pos = Util.getRecordType('Position__c', 'Annual Conference');
        RecordType RT_EI_pos = Util.getRecordType('Position__c', 'Educational Institutions');
        RecordType RT_CM_pos = Util.getRecordType('Position__c', 'Collegiate Ministry');
        RecordType RT_D_pos = Util.getRecordType('Position__c', 'District');
        
        Position__c pos_ac = new Position__c(RecordTypeId = RT_AC_pos.Id,
                                                       Contact__c = con.Id,
                                                       Organization_Name__c = org_CM.Id
                                                       );
        test.startTest();
        try{
                insert pos_ac;
            }
            catch (DmlException e){
                System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                    e.getMessage());
            }
        Position__c pos_EI = new Position__c(RecordTypeId = RT_EI_pos .Id,
                                                       Contact__c = con.Id,
                                                       Organization_Name__c = org_EI .Id
                                                       );
        insert pos_EI ;
        Position__c pos_EI1 = new Position__c (id = pos_EI.id,
                                               Contact__c = con.Id,
                                                Organization_Name__c = org_CM .Id
                                                       ); 
        try{
                update pos_EI1 ;
            }
            catch (DmlException e){
                System.debug('Organization Record Type should be Educational Institutions' + e);
            }                                                                                             
        test.stopTest();
    
    delete pos_EI ;
    delete con;
    }
   
    
}