xml/src2/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Annual_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Annual Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Annual Conference</relationshipLabel>
        <relationshipName>Annual_Conference</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

xml/src1/objects/Annual_Conference__c.object
<CustomObject>
    <description>Getting Annual Conferences depending on Episcopal Area</description>
    <fields>
        <fullName>Annual_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organization Annual Conference</description>
        <label>Annual Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Annual Conferences (Annual Conference)</relationshipLabel>
        <relationshipName>Annual</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Conference</label>
    <nameField>
        <displayFormat>AC-{00000000}</displayFormat>
        <label>AC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Conferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Annual_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A geographical area and organization. Defines a region that includes all UM churches and ministries in that area.</description>
        <inlineHelpText>Enter contact&apos;s home annual conference (where membership held)</inlineHelpText>
        <label>Annual Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Appointment_Conference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Most clergy will serve in the annual conference where their membership is held.  However, those in Extension Ministry/ABLC could serve in a different annual conference than where their membership is.Only clergy members should have an assigned Appointment Conference.  The Annual Conference where Contact is appointed to serve.</description>
        <inlineHelpText>If different from Annual Conference, enter annual conference where contact is appointed (working conference)</inlineHelpText>
        <label>Appointment Conference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Working Conference)</relationshipLabel>
        <relationshipName>Working_Conference</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salutation_Other__c</fullName>
        <description>Other Salutation for the contact</description>
        <inlineHelpText>Enter salutation if not found in Picklist</inlineHelpText>
        <label>Salutation Other</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

xml/src2/classes/UT_ContactUtil.cls
/**
 Raji : 08.10.2011
 1.Test class for Contact Util Functionality.
 */
@isTest
private class UT_ContactUtil 
{
    static testMethod void ContactUtil() 
    {
        UnitTest_Exception_Manager.ThrowException = true;
        
        //Test for Annual Conference & Appoitment Conference on Contact
        RecordType AccountAnnualConf = Util.getRecordType('Account', 'Annual Conference');
        Account account1 = new Account(
            Name = 'Annual Conference 1',
            RecordTypeId = AccountAnnualConf.Id
            );
        insert account1;
        
        Account account2 = new Account(
            Name = 'Annual Conference 2',
            RecordTypeId = AccountAnnualConf.Id
            );
        insert account2;
        
        Contact contact1 = new Contact(
            LastName = 'Last Name 1',
            Salutation = '',
            Salutation_Other__c = ' '
            );
        Contact contact2 = new Contact(
            LastName = 'Last Name 2',
            Salutation = '',
            Salutation_Other__c = 'test salutation',
            Annual_Conference__c = account1.Id
            );
        Contact contact3 = new Contact(
            LastName = 'Last Name 3',
            Salutation = 'Mr.',
            Salutation_Other__c = 'Miss'
            );
        /* Rocky Assad : TA616
        Contact contact4 = new Contact(
            LastName = 'Last Name 4',
            Salutation = 'The Rev.',
            Salutation_Other__c = '',
            Annual_Conference__c = account1.Id,
            Appointment_Conference__c = account2.Id
            );
        */
            
        test.startTest();
            
            //try{
                insert contact1;
           /* }
            catch (DmlException e){
                System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                    e.getMessage());
            }*/
            insert contact2;
            /* Rocky Assad : TA616
            insert contact4;
            */
            
            try{
                insert contact3;
            }
            catch (DmlException e){
                System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                    'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION'),
                    e.getMessage());
            }
            
            System.debug('Contact2'+ contact2);
                            
        test.stopTest();
        
        Contact contact1record = [SELECT LastName, Salutation, Salutation_Other__c FROM Contact WHERE Id =: contact1.Id];
        //Commented out only for migration phase. Rocky Assad 2/1/2012
        //System.assertEquals('The Rev.', contact1record.Salutation); 
        
        
        Contact contact2record = [SELECT LastName, Salutation, Salutation_Other__c, Annual_Conference__c, Appointment_Conference__c  FROM Contact WHERE Id =: contact2.Id];
        System.assertEquals('test salutation', contact2record.Salutation);
        /* Rocky Assad : TA616 
        System.assertEquals(contact2record.Appointment_Conference__c, contact2record.Annual_Conference__c); 
        */
        
        /* Rocky Assad : TA616
        Contact contact3record = [SELECT LastName, Salutation, Salutation_Other__c, Annual_Conference__c, Appointment_Conference__c  FROM Contact WHERE Id =: contact4.Id];
        System.assertNotEquals(contact3record.Appointment_Conference__c, contact3record.Annual_Conference__c);
        */ 
        
        delete contact1;
        delete contact2;
        /* Rocky Assad : TA616
        delete contact4;
        */
        
        delete account2;
        delete account1;
          
    }
    
 }