xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age trigger pop up field</description>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Comments any on Contacts</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DOB_Month__c</fullName>
        <description>DOB Month from Milestone</description>
        <label>DOB Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Date of Birth</description>
        <label>Date of Birth</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Death_Date__c</fullName>
        <description>Death date: Pop up&apos;s through trigger from Milestone object</description>
        <label>Death Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship for Formulas</description>
        <label>Milestone</label>
        <referenceTo>Milestones__c</referenceTo>
        <relationshipLabel>Contacts (Milestone)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Contact Status</description>
        <inlineHelpText>Select &apos;Inactive&apos; when entire contact record is no longer valid for communication</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

xml/src1/objects/Milestones__c.object
<CustomObject>
    <description>The Milestones of the Contact</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age Calculation</description>
        <formula>IF($RecordType.Name = &apos;Birth Date&apos; &amp;&amp;  ISPICKVAL( Milestone__c ,&apos;Birth Date&apos;) &amp;&amp; NOT( ISBLANK(Birth_Date__c) ) &amp;&amp; ISBLANK(Death_Date__c)
, FLOOR((TODAY()-Birth_Date__c+1)/365.2425)
,  IF($RecordType.Name = &apos;Death Date&apos; &amp;&amp;  ISPICKVAL( Milestone__c ,&apos;Death Date&apos;)
, 0
,null) )</formula>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Birth_Date__c</fullName>
        <description>Birth Date of Contact</description>
        <label>Birth Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Any details that need to be known on the milestone</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Master detail relationship</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Start date of the Milestone</description>
        <inlineHelpText>Enter Milestone start date here</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Death_Date__c</fullName>
        <description>Death Date of the Contact</description>
        <label>Death Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <description>Milestones of the contact</description>
        <label>Milestone</label>
        <picklist>
            <picklistValues>
                <fullName>Affiliate Member with a Vote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birth Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bishop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bishop Retirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Deacon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Elder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Local Pastor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Undecided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified Lay Minister</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deacon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Death Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Death in Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divorced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full-Time Local Pastor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honorable Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minister Other Denomination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Name Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other than Honorable Discharge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <displayFormat>Milestone-{00000000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src2/classes/UT_MilestoneContact.cls
/**
 Raji : 08.10.2011
 Test class for Milestone Contact Functionality Functionality.
 Raji : 1/05/2011
 Updated Birth date & Death Date as 2 different fields
 */
@isTest
private class UT_MilestoneContact 
{
    static testMethod void MilestoneContact() {
        UnitTest_Exception_Manager.ThrowException = true;
        
        Contact contact1 = new Contact(
            LastName = 'Last Name',
            Salutation = 'Mr.'
            );
        test.startTest();
        insert contact1;
        
        Milestones__c milestone1 = new Milestones__c(
            Contact__c = contact1.Id,
            Milestone__c = 'Birth Date',
            Birth_Date__c = Date.valueOf('1990-08-10') //date.newinstance(1990, 2, 17) //1990-08-10
            );
            System.debug('Birth Date'+milestone1.Birth_Date__c);
        
        insert milestone1;
        
        milestone1.Comments__c = 'something';
        update milestone1;
        
        Milestones__c milestone2 = new Milestones__c(
            Contact__c = contact1.Id,
            Milestone__c = 'Death Date',
            Death_Date__c = Date.today() 
            );
            
        insert milestone2;
        
        test.stopTest();
        
        Contact contact1record = [SELECT LastName, Salutation, Age__c, Death_Date__c, DOB_Month__c, Date_of_Birth__c,Status__c  FROM Contact WHERE Id =: contact1.Id];
        Milestones__c milestone1record = [SELECT Contact__c, Milestone__c, Birth_Date__c, Death_Date__c, Date__c, Age__c FROM Milestones__c WHERE Id =: milestone1.Id];
        System.assertEquals(milestone1record.Age__c, contact1record.Age__c);
        System.debug('contact1record.Date_of_Birth__c : '+contact1record.Date_of_Birth__c);
        System.debug('contact1record.DOB_Month__c :'+contact1record.DOB_Month__c);
        
        Milestones__c milestone2record = [SELECT Contact__c, Milestone__c, Birth_Date__c, Death_Date__c, Date__c  FROM Milestones__c WHERE Id =: milestone2.Id];
       // System.assertEquals(milestone2record.Death_Date__c, contact1record.Death_Date__c); 
       // System.assertEquals('Inactive', contact1record.Status__c);
        
       
        delete milestone1; 
        delete milestone2;
        delete contact1;
    }
}