xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Contact Status</description>
        <inlineHelpText>Select &apos;Inactive&apos; when entire contact record is no longer valid for communication</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

xml/src2/objects/Course_Record__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <inlineHelpText>Enter amount candidate paid to GBHEM</inlineHelpText>
        <label>Amount Paid</label>
        <picklist>
            <picklistValues>
                <fullName>150.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>175.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other/Specify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Class_Type__c</fullName>
        <inlineHelpText>Select type that best describes course medium</inlineHelpText>
        <label>Class Type</label>
        <picklist>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact Registered for the courses</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Record</relationshipLabel>
        <relationshipName>Course_Record</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Courses__c</referenceTo>
        <relationshipLabel>Course Records</relationshipLabel>
        <relationshipName>Course_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Hour_Types__c</fullName>
        <description>credit hours types for each of the courses</description>
        <label>Credit Hour Types</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBHEM Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semester Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Units</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Credit_Hours__c</fullName>
        <description>credit hours for each of the courses</description>
        <inlineHelpText>Enter number of credit hours for course. If unknown, enter 0</inlineHelpText>
        <label>Credit Hours</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GBHEM_DataCenter_grade__c</fullName>
        <description>GBHEM DataCenter: table = course_person field = grade</description>
        <inlineHelpText>Enter only information for the Data Center</inlineHelpText>
        <label>GBHEM DataCenter grade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <picklist>
            <picklistValues>
                <fullName>A+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trans Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course Record</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Course Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Record</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src1/objects/Courses__c.object
<CustomObject>
    <fields>
        <fullName>Course_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this relationship is created for Roll up Credit Hours for each of teh course for the contacts</description>
        <label>Course Record</label>
        <referenceTo>Course_Record__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Course Name</description>
        <inlineHelpText>Course Name</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Select course status.  Inactive status is only for courses no longer offered.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000000}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src2/classes/UT_Course_Rec_DefaultAmount.cls
/**
 Raji : removed Transcript Info and Course Record & Course Field Changes Updated
  */
@isTest
private class UT_Course_Rec_DefaultAmount 
{
    static testMethod void Course_Record_DefaultAmountPaid_Single()
    {
        UnitTest_Exception_Manager.ThrowException = true;
        
        // Grab Advanced COS Record Type
        RecordType rtAdvCOS = Util.getRecordType('Course_Record__c', 'Advanced Course of Study');
        
        // Create a Contact in order to create a Transcript Information record
        Contact contact = new Contact(FirstName = 'Rocky', 
                                       LastName = 'Assad_01',
                                       Salutation = 'Mr.');
                                       
        insert contact;
         RecordType recordType1 = Util.getRecordType('Courses__c', 'Advanced Course of Study');
        Courses__c course = new Courses__c(RecordTypeId = recordType1.Id,
                                           Name__c = 'Some Course',
                                           Status__c = 'Active');
                                           
        insert course;
        
                            
        // Create Course Record with Advanced COS Record Type and Class Type of Online
        Course_Record__c courseRecord = new Course_Record__c(Contact__c = contact.Id,
                                                             GBHEM_DataCenter_grade__c = 'test',
                                                             Grade__c = 'A',
                                                             Credit_Hour_Types__c = 'Quarter Hours',
                                                             Credit_Hours__c = 10,
                                                             Course__c = course.Id,
                                                             RecordTypeId = rtAdvCOS.Id,
                                                             Class_Type__c = 'Online',
                                                             Amount_Paid__c = null);

        test.startTest();
        
        // Should update Amount Paid to 175
        insert courseRecord;
        
        // Query Course Record with Amount Paid in order to Assert Amount Paid
        courseRecord = [SELECT Id, Amount_Paid__c FROM Course_Record__c WHERE Id = :courseRecord.Id];
        
        System.assertEquals('175.00', courseRecord.Amount_Paid__c);
        
        // Change Class Type to Correspondence
        courseRecord.Class_Type__c = 'Correspondence';
        courseRecord.Amount_Paid__c = null;
        
        // Should update Amount Paid to 150 
        update courseRecord;
        
        // Query Course Record with Amount Paid in order to Assert Amount Paid
        courseRecord = [SELECT Id, Amount_Paid__c FROM Course_Record__c WHERE Id = :courseRecord.Id];
        
        System.assertEquals('150.00', courseRecord.Amount_Paid__c);
        
        test.stopTest();
    }
}