xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Contact Status</description>
        <inlineHelpText>Select &apos;Inactive&apos; when entire contact record is no longer valid for communication</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

xml/src2/objects/Course_Record__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact Registered for the courses</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Record</relationshipLabel>
        <relationshipName>Course_Record</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Courses__c</referenceTo>
        <relationshipLabel>Course Records</relationshipLabel>
        <relationshipName>Course_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Hour_Types__c</fullName>
        <description>credit hours types for each of the courses</description>
        <label>Credit Hour Types</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBHEM Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semester Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Units</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Credit_Hours__c</fullName>
        <description>credit hours for each of the courses</description>
        <inlineHelpText>Enter number of credit hours for course. If unknown, enter 0</inlineHelpText>
        <label>Credit Hours</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scholarship_Date__c</fullName>
        <inlineHelpText>Enter date of scholarship status event</inlineHelpText>
        <label>Scholarship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scholarship_Status__c</fullName>
        <label>Scholarship Status</label>
        <picklist>
            <picklistValues>
                <fullName>Applied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course Record</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Course Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Record</pluralLabel>
    <recordTypes>
        <fullName>BGTS</fullName>
        <active>true</active>
        <description>Basic Graduate Theological Study Courses</description>
        <label>BGTS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src1/objects/Courses__c.object
<CustomObject>
    <fields>
        <fullName>Course_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this relationship is created for Roll up Credit Hours for each of teh course for the contacts</description>
        <label>Course Record</label>
        <referenceTo>Course_Record__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Select course status.  Inactive status is only for courses no longer offered.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000000}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>BGTS</fullName>
        <active>true</active>
        <description>Basic Graduate Theological Study Courses</description>
        <label>BGTS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src2/classes/UT_Course_Record_InsertAward.cls
@isTest
//Raji : Commented To Hide Awards Functionality
private class UT_Course_Record_InsertAward 
{	
	/*Raji
    static testMethod void CreateCourseAwardAysnc() 
    {
        UnitTest_Exception_Manager.ThrowException = true;
        
        // create contact
        Contact contact = new Contact(Email = 'test@test0101010.com', 
                                      FirstName = 'Rocky', 
                                      LastName = 'Assad_01',
                                      Salutation = 'Mr.');
                                      
        insert contact;
                        
        // create course
        RecordType recordType1 = Util.getRecordType('Courses__c', 'BGTS');
        Courses__c course = new Courses__c(RecordTypeId = recordType1.Id,
                                           Name = 'Some Course',
                                           Status__c = 'Active');
                                           
        insert course;
        
        // create course record
        RecordType recordType2 = Util.getRecordType('Course_Record__c', 'BGTS');
        Course_Record__c record = new Course_Record__c(RecordTypeId = recordType2.Id,
                                                       Contact__c = contact.Id,
                                                       Credit_Hours__c = 10,
                                                       Credit_Hour_Types__c = 'Quarter Hours',
                                                       Course__c = course.Id,
                                                       Scholarship_Status__c = 'Approved',
                                                       Scholarship_Date__c = date.today());
        test.startTest();
        insert record;
        test.stopTest();
        
        Integer cnt = [select COUNT() from Awards__c where Contact__c = :contact.Id];
        
        System.assertEquals(1, cnt);
    }Raji*/
}