xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age trigger pop up field</description>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DOB_Month__c</fullName>
        <description>DOB Month from Milestone</description>
        <label>DOB Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Date of Birth</description>
        <label>Date of Birth</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Death_Date__c</fullName>
        <description>Death date: Pop up&apos;s through trigger from Milestone object</description>
        <label>Death Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship for Formulas</description>
        <label>Milestone</label>
        <referenceTo>Milestones__c</referenceTo>
        <relationshipLabel>Contacts (Milestone)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Contact Status</description>
        <inlineHelpText>Select &apos;Inactive&apos; when entire contact record is no longer valid for communication</inlineHelpText>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

xml/src1/objects/Milestones__c.object
<CustomObject>
    <description>The Milestones of the Contact</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age Calculation</description>
        <formula>IF($RecordType.Name = &apos;Birth Date&apos; &amp;&amp;  ISPICKVAL( Milestone__c ,&apos;Birth Date&apos;) &amp;&amp; NOT( ISBLANK(Birth_Date__c) ) &amp;&amp; ISBLANK(Death_Date__c)
, FLOOR((TODAY()-Birth_Date__c+1)/365.2425)
,  IF($RecordType.Name = &apos;Death Date&apos; &amp;&amp;  ISPICKVAL( Milestone__c ,&apos;Death Date&apos;)
, 0
,null) )</formula>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Birth_Date__c</fullName>
        <description>Birth Date of Contact</description>
        <label>Birth Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Master detail relationship</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Death_Date__c</fullName>
        <description>Death Date of the Contact</description>
        <label>Death Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <description>Milestones of the contact</description>
        <label>Milestone</label>
        <picklist>
            <picklistValues>
                <fullName>Affiliate Member with a Vote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birth Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bishop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bishop Retirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Deacon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Elder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Local Pastor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Undecided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified Lay Minister</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deacon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Death Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Death in Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divorced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full-Time Local Pastor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honorable Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minister Other Denomination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Name Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other than Honorable Discharge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <displayFormat>Milestone-{00000000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src2/classes/Handler_Milestones.cls
public with sharing class Handler_Milestones
{
    /*Raji : 06.09.2011
        Functionality : to pop the fields from Milestones Object to Contact
    */
    public static void UpdateContactAge(List<Milestones__c> newMilestones)
    {
        
         RecordType milestoneDeath = Util.getRecordType('Milestones__c', 'Death Date');
         RecordType milestoneBirth= Util.getRecordType('Milestones__c', 'Birth Date');
        
        Set<Id> conIds = new Set<Id>();
        for(Milestones__c milestone : newMilestones)
        {
            conIds.add(milestone.contact__c);
        }
        
        Map<Id,contact> contactMap = new Map<Id,Contact>([Select id, Age__c,Death_Date__c,DOB_Month__c,Date_of_Birth__c,Status__c from contact where Id IN :conIds]);
        Map<Id,Contact> updatedContactMap = new Map<id,Contact>();
        
        //Milestone Age
        for(Milestones__c milestone : newMilestones)
        {
            if((milestone.RecordTypeId == milestoneBirth.Id ||milestone.RecordTypeId == milestoneDeath .Id )&& milestone.Age__c != null)
            {
                Contact con = contactMap.get(milestone.contact__c);
                con.Age__c = milestone.Age__c;
                updatedContactMap.put(con.id,con);
            }
            
            
            //Milestone Death 
            if(milestone.RecordTypeId == milestoneDeath .Id && milestone.Milestone__c == 'Death Date'){
                Contact con = contactMap.get(milestone.contact__c);
                if(milestone.Death_Date__c !=null)con.Death_Date__c = milestone.Death_Date__c;
                con.Status__c = 'Inactive';
                updatedContactMap.put(con.id,con);
            }
            //Milestone Birth
            if(milestone.RecordTypeId == milestoneBirth.Id && milestone.Milestone__c == 'Birth Date'){
                Contact con = contactMap.get(milestone.contact__c);
                if(milestone.Birth_Date__c !=null)
                con.Date_of_Birth__c = milestone.Birth_Date__c.month()+ '/'+ milestone.Birth_Date__c.Day();
                con.DOB_Month__c = milestone.Birth_Date__c.month();
                
                
                updatedContactMap.put(con.id,con);
            }
       
        }
        if(updatedContactMap.size() > 0)
        {
            update updatedContactMap.values();
        }
    }
        
 }