xml/src2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Appointment__c</fullName>
        <description>Appointments for the contact</description>
        <label>Appointment</label>
        <picklist>
            <controllingField>Ministry_Category__c</controllingField>
            <picklistValues>
                <fullName>Local Church</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beyond the Local Church</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extension Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attend School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conference Membership Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Terminated by AC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred to Licensed or Ordained Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dual_Appointment__c</fullName>
        <description>Second appointment for the Ministry Category Contacts</description>
        <inlineHelpText>If dual appointed, enter second appointment here.</inlineHelpText>
        <label>Dual Appointment</label>
        <picklist>
            <controllingField>Ministry_Category__c</controllingField>
            <picklistValues>
                <fullName>Local Church</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beyond the Local Church</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extension Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attend School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conference Membership Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Terminated by AC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred to Licensed or Ordained Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

xml/src1/objects/Education_Information__c.object
<CustomObject>
    <description>The type and level of education an individual has received in a particular area.</description>
    <fields>
        <fullName>Education_Detail__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Education Detail</relationshipLabel>
        <relationshipName>Education_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Education_Type__c</fullName>
        <description>A particular group or class of education.</description>
        <inlineHelpText>Select the Education Type that most accurately describes the degree/education experience</inlineHelpText>
        <label>Education Type</label>
        <picklist>
            <picklistValues>
                <fullName>Highest Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undergrad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate/Post Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminary/Theological</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Pastor Licensing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other/Specify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field_of_Study__c</fullName>
        <inlineHelpText>Enter major field or concentration</inlineHelpText>
        <label>Field of Study</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Highest_Education__c</fullName>
        <inlineHelpText>Select highest education level contact has attained</inlineHelpText>
        <label>Highest Education</label>
        <picklist>
            <controllingField>Education_Type__c</controllingField>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Some College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Some Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate/Post Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Education Information</label>
    <nameField>
        <displayFormat>Edu-{00000000}</displayFormat>
        <label>Education ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src1/classes/UT_Education_OnlyOneHighestEd.cls
/* Rocky: 05/26/2011
    Trigger UnitTest: Education_OnlyOneHighestEd.
*/
@isTest
private class UT_Education_OnlyOneHighestEd 
{
    static testMethod void Education_OnlyOneHighestEd() 
    {
        UnitTest_Exception_Manager.ThrowException = true;
        
        // Rocky Assad
        // Create and account just to ensure that ACCOUNT_GBHEM_CONSTITUENT_ACCOUNT_NAME
        // is created prior to folling tests.
        Contact contactPrior = new Contact(FirstName = 'TestUserSetup', 
                                           LastName = 'UserSetup',
                                           Salutation = 'Mr.',
                                           Appointment__c = 'Local Church',
                                           Dual_Appointment__c= '');
                                           
        insert contactPrior;
        
        Account account = [SELECT Id FROM Account WHERE Name = 'GBHEM Constituent' limit 1];
        Contact contact = new Contact(AccountId = account.Id, 
                                          FirstName = 'Test', 
                                          LastName = 'User',
                                          Salutation = 'Mr.',
                                          Appointment__c = 'Local Church',
                                          Dual_Appointment__c= '');
                                          

        insert contact;
        
        // Stop the test, this changes limit context back to test from trigger.
        for(Integer i = 0; i < 2; i++) {
            
            Education_Information__c education = new Education_Information__c(Education_Type__c = 'Highest Education', 
                                                                                Highest_Education__c = 'High School',
                                                                                Education_Detail__c = contact.id);
                                          
            try 
            {                                                           
                insert education;
                
                if(i == 0)
                {
                    education.Field_of_Study__c = 'new';
                    update education;
                }
            } 
            catch(DmlException ex) 
            {
                System.assert(ex.getMessage().contains('Highest Education may only be added once for any given contact'), ex.getMessage());
            }
        }
    }
    
    //Raji : 11/16/2011 
    //Local Pastor Licensing Unit Test
     static testMethod void Education_OnlyOneLocalPastorLicensing(){
        UnitTest_Exception_Manager.ThrowException = true;
        
        // Create and account just to ensure that ACCOUNT_GBHEM_CONSTITUENT_ACCOUNT_NAME
        // is created prior to following tests.
        Contact contactPrior = new Contact(FirstName = 'Test', 
                                           LastName = 'User',
                                           Salutation = 'Mr.',
                                           Appointment__c = 'Local Church',
                                           Dual_Appointment__c= '');
                                           
        insert contactPrior;
        
        Account account = [SELECT Id FROM Account WHERE Name = 'GBHEM Constituent' limit 1];
        Contact contact = new Contact(AccountId = account.Id, 
                                          FirstName = 'Test', 
                                          LastName = 'User1',
                                          Salutation = 'Mr.',
                                          Appointment__c = 'Local Church',
                                          Dual_Appointment__c= '');
                                          

        insert contact;
        
        // Stop the test, this changes limit context back to test from trigger.
        for(Integer i = 0; i < 2; i++) {
            
            Education_Information__c education = new Education_Information__c(Education_Type__c = 'Local Pastor Licensing', 
                                                                              Education_Detail__c = contact.id);
                                          
            try 
            {                                                           
                insert education;
                
                if(i == 0)
                {
                    education.Field_of_Study__c = 'new';
                    update education;
                }
            } 
            catch(DmlException ex) 
            {
                System.assert(ex.getMessage().contains('Local Pastor Licensing may only be added once for any given contact'), ex.getMessage());
            }
        }
        delete contact;
        delete contactPrior;
        
    }
}