xml/src2/objects/Course_Record__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <inlineHelpText>Enter amount candidate paid to GBHEM</inlineHelpText>
        <label>Amount Paid</label>
        <picklist>
            <picklistValues>
                <fullName>150.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>175.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other/Specify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Class_Type__c</fullName>
        <inlineHelpText>Select type that best describes course medium</inlineHelpText>
        <label>Class Type</label>
        <picklist>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact Registered for the courses</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Record</relationshipLabel>
        <relationshipName>Course_Record</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Courses__c</referenceTo>
        <relationshipLabel>Course Records</relationshipLabel>
        <relationshipName>Course_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GBHEM_DataCenter_grade__c</fullName>
        <description>GBHEM DataCenter: table = course_person field = grade</description>
        <inlineHelpText>Enter only information for the Data Center</inlineHelpText>
        <label>GBHEM DataCenter grade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <picklist>
            <picklistValues>
                <fullName>A+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trans Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scholarship_Date__c</fullName>
        <inlineHelpText>Enter date of scholarship status event</inlineHelpText>
        <label>Scholarship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scholarship_Status__c</fullName>
        <label>Scholarship Status</label>
        <picklist>
            <picklistValues>
                <fullName>Applied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course Record</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Course Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Record</pluralLabel>
    <recordTypes>
        <fullName>BGTS</fullName>
        <active>true</active>
        <description>Basic Graduate Theological Study Courses</description>
        <label>BGTS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

xml/src1/objects/Courses__c.object
<CustomObject>
    <fields>
        <fullName>Course_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this relationship is created for Roll up Credit Hours for each of teh course for the contacts</description>
        <label>Course Record</label>
        <referenceTo>Course_Record__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Course Name</description>
        <inlineHelpText>Course Name</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>Course-{00000000}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>BGTS</fullName>
        <active>true</active>
        <description>Basic Graduate Theological Study Courses</description>
        <label>BGTS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

xml/src2/classes/Handler_Course_Record.cls
public with sharing class Handler_Course_Record
{
    // Use @future methods when possible in AFTER operations. Note that the future method will 
    // not accept strongly typed collections... use Set<Id> and re-query the data. You can then 
    // pass in the keySet()
    
    /*Raji : Commenting to Hide Award Functionality
    @future
    public static void CreateCourseAwardAysnc(Set<Id> newCourseRecIds)
    {
        // local vars
        Set<Id> contactIds = new Set<Id>();
        List<Course_Record__c> courseRecsToAdd = new List<Course_Record__c>();
        List<Awards__c> awardsToAdd = new List<Awards__c>();
        
        // pre-process
        List<Course_Record__c> newCourseRecs = [select Id, RecordType.Name, Scholarship_Status__c, Scholarship_Date__c, Contact__c from Course_Record__c where Id in :newCourseRecIds];
        
        // grab all contact id's
        for(Course_Record__c course : newCourseRecs)
        {
            contactIds.Add(course.Contact__c);
        }
        
        List<Awards__c> contactsWithAwards = [select Id, Contact__c from Awards__c where Name__c = 'Course Scholarship' and Contact__c in :contactIds];
        
        // loop through all course records
        for(Course_Record__c courseRec : newCourseRecs)
        {
            // check if can recieve award
            if((courseRec.Scholarship_Status__c == 'Approved') && 
                (courseRec.RecordType.Name == 'Advanced Course of Study' || courseRec.RecordType.Name == 'Cert in Specialized Ministry' || courseRec.RecordType.Name == 'BGTS'))
            {
                // check if contact already has an award
                Boolean add = true;
                for(Awards__c contactWithAward : contactsWithAwards)
                {
                    if(courseRec.Contact__c == contactWithAward.Contact__c)
                    {
                        add = false;
                    }
                }
                
                if(add)
                {
                    // create award
                    Awards__c award = new Awards__c(Name__c = 'Course Scholarship', 
                                                    Course_Record__c = courseRec.Id, 
                                                    Contact__c = courseRec.Contact__c, 
                                                    Date_Awarded__c = courseRec.Scholarship_Date__c);
                    awardsToAdd.Add(award);
                }
            }
        }
        
        // insert awards
        insert awardsToAdd;
    }Raji*/
    
    public static void RemoveHistoricalGrade(List<Course_Record__c> newCourseRecs, Map<Id, Course_Record__c> oldCourseRecs)
    {
        for(Course_Record__c courseRecord : newCourseRecs) 
        {
            if((courseRecord.Grade__c != oldCourseRecs.get(courseRecord.id).Grade__c) &&
                courseRecord.GBHEM_DataCenter_grade__c != null) 
            {
                
                courseRecord.GBHEM_DataCenter_grade__c = null;
            }
        }
    }
    
    public static void DefaultAmountPaid(List<Course_Record__c> newCourseRecs)
    {
        RecordType recordType = Util.getRecordType('Course_Record__c', 'Advanced Course of Study');

        for(Course_Record__c courseRecord : newCourseRecs) {
            
            if(recordType.Id == courseRecord.RecordTypeId) {
                
                if(courseRecord.Class_Type__c == 'Online') {
                    
                    if(courseRecord.Amount_Paid__c == null || courseRecord.Amount_Paid__c == '') {
                        
                        courseRecord.Amount_Paid__c = '175.00';
                    }
                } else if (courseRecord.Class_Type__c == 'Correspondence') {
                    
                    if(courseRecord.Amount_Paid__c == null || courseRecord.Amount_Paid__c == '') {
                        
                        courseRecord.Amount_Paid__c = '150.00';
                    }
                }
            }
        }
    }
    
    //Raji : 2/20/2012
    //Rocky Assad : 2/29/2012 
    //Logic to avoid Lookup Filter Limitation Validation rule
    public static void CR_LookupFilterValidation(List<Course_Record__c> newCR)
    {
        for(Course_Record__c corRec : newCR)
        {
            if((corRec.Course__c != null) && (corRec.RecordType.Name != corRec.Course__r.RecordType.Name))
            {
                corRec.addError('The course\'s record type should match that of the course.');
            }
        }
    }
}